### ISSUE TITLE
Windows Cuda build is broken

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#1012]
Dmitry's patch https://github.com/ceres-solver/ceres-solver/commit/18ea7d1c218275d09715cbdb6d54c2818d678a05 broke the windows and linux build. I fixed the linux build in https://github.com/ceres-solver/ceres-solver/commit/bea24770109f87160b96e1583199d82100c3ed6c which I thought would fix both builds, but the VisualStudio build is still broken.

https://github.com/ceres-solver/ceres-solver/actions/runs/6279749583/job/17055916387

and it seems to be related to not being able to find glog for the cuda kernels build target.

**Comment by sandwichmaker** [comment]
@sergiud can you please take a look?

**Comment by sandwichmaker** [comment]
cc: @DmitriyKorchemkin happy to assign this to you.

**Comment by sandwichmaker** [comment]
@sergiud @DmitriyKorchemkin is looking into this.

**Comment by DmitriyKorchemkin** [comment]
I have three solutions in mind:
 
 1. Add dependencies of  `ceres` to `ceres_cuda_kernels`.
     Just adding dependencies via `target_link_libraries` does not resolve the problem completely (`nvcc` version that we have on windows does not support nested namespaces, and `ContextImpl` references lots of stuff via `ThreadPool`)
 1. Move cuda-related stuff from `ContextImpl` into a separate structure inside `ceres_cuda_kernels`, and add it as a field to `ContextImpl`
 1. Use implementation from the first version of patchset (with boolean flag instead of passing `ContextImpl`)
 
Which one makes more sense from your perspective?

**Comment by sandwichmaker** [comment]
I think (1) is going to be a pain.
(2) requires design, I'd rather do it in the 2.3 timeframe, and for now lets go back to (3) for now.

**Comment by sandwichmaker** [comment]
Fixed at head
