### ISSUE TITLE
Merely including Ceres header file causes LNK2019 error (unresolved external symbol) from MSVC.

### ISSUE THREAD

**Issue by capn-freako** [ceres-solver/ceres-solver#1044]
Hi,

I'm waiting to be added to the Google group.
So, posting this here in the meantime, hoping this is a known issue.
I'm getting a LNK2019 error from the Microsoft linker when I merely include the Ceres header file.
I don't even need to call any Ceres library functions!
I've put all the details in the following _Stack Overflow_ question:

[SO question](https://stackoverflow.com/questions/77876493/why-does-merely-including-ceres-headers-cause-link-errors-due-to-missing-symbol)

Thanks!
-db
:)

**Comment by capn-freako** [comment]
Thank you! I’ll post my question to the list; maybe, someone knows where I’ve screwed up.
It’s probably something really stupid. These really weird ones always are. ;-)

Thanks for the public domain optimizer!
-db

**Comment by sergiud** [comment]
This seems to be a compiler setup issue. The linker warnings/errors stem from standard library symbols not Ceres.

How did you compile Ceres (or other link libraries for that matter)? Likely your project links against a different [runtime library](https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170)  than the one used to compile Ceres. Check your compiler flags.

Different CMake versions might also cause problems because CMake 3.15 changed [the way the runtime library is selected](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html).

Finally, you must use CMake (or Bazel) to actually integrate Ceres into your project. Ceres sets different flags and link dependencies which you would need to exactly replicate. Incorrectly replicating compiler flags required by CMake might cause such issues as well.

**Comment by sandwichmaker** [comment]
I think this has been solved by add "/MD".
