### ISSUE TITLE
polynomial fit API in ceres?

### ISSUE THREAD

**Issue by rursprung** [ceres-solver/ceres-solver#1109]
a while ago i needed a polyfit functionality in C++ and ended up writing [a small 2D polyfit header-only library](https://github.com/Nic822/banana-project/blob/master/include/polyfit/Polynomial2DFit.hpp) ([incl. test coverage](https://github.com/Nic822/banana-project/blob/master/test/polyfit-test.cpp)) based on ceres.

i'm wondering if it would make sense to add this (possibly with some changes) directly to ceres?
changes which i could imagine:
* remove C++23 & C++20 features to match ceres' C++17 standard (unless ceres is ready to upgrade? :wink:)
* make it a generic n-D polyfit (not sure how to do this in a performant way, maybe can be achieved using some template voodoo? otherwise needs runtime loops)

this would provide a commonly used convenience method directly to ceres and thus make it available to the wider C++ ecosystem (e.g. in python there are many libraries providing such a method, see for example [my test from the other repo](https://github.com/Nic822/banana-project/blob/master/docs/banana-center-line-fitting.ipynb) for some of them).

note that the repo where i published this is licensed under GPL, but i'm ok with re-licensensing the 2D polyfit part (header + test + related infrastructure code) to the (custom?) license used in ceres.

**Comment by sergiud** [comment]
I'm not sure I understand the purpose. (Multivariate) polynomial fitting is a linear least-squares problem. Why do you need Ceres for this?

**Comment by rursprung** [comment]
> Why do you need Ceres for this?

because Ceres was easy to use in this case and i didn't find a simpler library i could use instead.

**Comment by sergiud** [comment]
That's not really meaningful because the problem can be solved optimally without Ceres, e.g., using QR decomposition or SVD in the general case.

At this point, the library also seems to be limited to second-order univariate polynomials which is prohibitive in many real world cases. Therefore, I suggest looking into expanding the library to support
* arbitrary degree polynomials
* multiple independent variables (tensor product over multiple univariate polynomials)
* linear least squares fit
* computing the gradient w.r.t. to free variables

These features would facilitate the use of the library in many other scenarios, for instance, to represent (smooth) surfaces in 3-D and actually justify the use in combination with Ceres, e.g., computing orthogonal contact points.

**Comment by rursprung** [comment]
thanks for the suggestions, @sergiud!
i currently do not have the time (or need) for these extensions, i just built that header to solve a specific need of mine (in a toy project which is now finished) and thought i'd put it out here in case anyone sees a need for it and wants to incorporate it.

if anyone wants to pick this up and wants to use my code as a starting point: i grant you the code relevant also under the license used in the ceres project.

**Comment by sandwichmaker** [comment]
As @sergiud points out polynomial fitting does not require the use of Ceres Solver (you certainly can use it, but just a linear algebra library is enough). So while your offer is kind, but you are not willing to extend/maintain the library we cannot accept this into the library.
