### ISSUE TITLE
Strict Eigen version matching

### ISSUE THREAD

**Issue by soesau** [ceres-solver/ceres-solver#1115]
Using a built ceres lib with a more recent version of Eigen is rejected:

> Found Eigen dependency, but the version of Eigen found (3.4.90) does not exactly match the version of Eigen Ceres was compiled with (3.4.0). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details

Why is the matching so strict? Compatibility should be given for newer versions unless the major version changes. I saw it was added 9 years ago, is it still necessary?

This makes testing on our side much more cumbersome.

**Comment by soesau** [comment]
https://github.com/CGAL/cgal/issues/8596

**Comment by sergiud** [comment]
The error message already explains why a strict version matching is necessary. To expand on that, the use of expression templates pretty much inhibits a stable ABI which can lead to ODR violations if different versions of the library are intermixed in the same binary. This is regardless whether Eigen is actually used in Ceres' (or any other) API since the issues can be triggered by instantiations of various expression templates across multiple translation units. What's worse, compilers are the not required to diagnose such issues.

Aside from that, there is no new version of Eigen. The latest Eigen release at this point is 3.4.0. You are likely using a development version of Eigen.
