### ISSUE TITLE
Error detecting Eigen3_VERSION

### ISSUE THREAD

**Issue by jan-marchant** [ceres-solver/ceres-solver#1118]
I'm not sure whether this is a ceres-solver issue, an Eigen3 issue, or just my issue. I have used homebrew on MacOS to install ceres-solver and all of its dependencies including Eigen3. When I try to make a project that depends on ceres-solver I get the following error:

> CMake Error at /opt/homebrew/lib/cmake/Ceres/CeresConfig.cmake:89 (message):
  Failed to find Ceres - Found Eigen dependency, but the version of Eigen
  found () does not exactly match the version of Eigen Ceres was compiled
  with (3.4.0).

This is because `/opt/homebrew/lib/cmake/Ceres/CeresConfig.cmake` expects `Eigen3_VERSION` to be set by `find_package`, but `/opt/homebrew/share/cmake/Modules/FindEigen3.cmake` only defines `EIGEN3_VERSION`. I have resolved this by modifying `/opt/homebrew/share/cmake/Modules/FindEigen3.cmake` to also set `Eigen3_VERSION`.

My guess is that it's more appropriate that this is fixed here, but if not I'm happy to report elsewhere.

**Comment by sergiud** [comment]
Ceres expects a proper `Eigen3Config.cmake` package configuration as it has been officially [supported by Eigen](https://gitlab.com/libeigen/eigen/-/commit/a287140f7292b9c15719bc6a3a4494ac7874e3cd#a041c2d3b00e385b227af53825a35e73c62c55fb)  for many years, but at least since version 3.3.1 of the library. `FindEigen3.cmake` was the initial approach to provide CMake support for Eigen which required copying the module into every project that used the module. This approach caused many issues and the module was therefore [removed in 2021](https://gitlab.com/libeigen/eigen/-/commit/f2984cd0778dd0a1d7e74216d826eaff2bc6bfab).

I suggest asking whoever packages `FindEigen3.cmake` to remove the file and switch to the officially supported Eigen package configuration.

**Comment by jan-marchant** [comment]
OK thank you. It looks like the homebrew eigen formula is the culprit.

Until this is resolved I think that any macOS installs that follow the recommended installation instructions (http://ceres-solver.org/installation.html#macos) will have this issue.

**Comment by sergiud** [comment]
This is entirely possible. However, to workaround this upstream issue we would need to raise our minimum CMake version requirement since CMake 3.16 does not allow to disable the search in module mode for individual `find_package` invocations. This seems a bit excessive.

You can possibly avoid the issue by setting the [`CMAKE_FIND_PACKAGE_PREFER_CONFIG`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html#variable:CMAKE_FIND_PACKAGE_PREFER_CONFIG) variable to `ON`.

**Comment by sergiud** [comment]
I'll close the issue since the problem was fixed by the upstream.
