### ISSUE TITLE
Allow the user to supply their own evaluator

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#174]
Currently the user has to use the problem interface and depend on ceres's evaluator implementation to use the solver. For some problems ceres' evaluation model is not fit for the user. For example if they want to bulk evaluate or share evaluation data between residual blocks, or if they want to perform the evaluation on the GPU.

To this end, it would be useful to allow the user to supply an evaluator object as input to ceres instead of a problem object. This evaluator will be responsible for supplying residuals & jacobian matrices on demand.

**Comment by spinicist** [comment]
If I understand correctly, this is exactly the feature I want and am surprised is missing.

The cost functions I use have a small number of parameters, known at compile time, and a larger number of residuals, only known at run time. I already have these cost functions written to take an `Eigen::VectorXd` of data-points and calculate all the residuals in one go.

Looking at the ceres interface, I think I would have to rewrite these to calculate one residual at a time. As there are a lot of calculations that can be shared across residuals, this is disappointing.

**Comment by alexsmac** [comment]
This depends on the sparsity pattern of your problem, the implication from what you describe is that your problem is dense - all the residuals in your VectorXd are dependent upon all of the parameters.  Ceres allows both residual blocks and parameter blocks, but considers sparsity only at the level of blocks.  So in your case, you could have a single CostFunction that takes in a single parameter block that contains the subset of parameters on which all the residuals are dependent, and outputs an Nx1 residual block containing the contents of the VectorXd you calculate.

This issue relates to a different use case, which is when the problem is sparse, so blocks are mathematically independent, but as in the GPU case it is faster to compute all residuals & jacobians at once at each iteration (irrespective of whether the solver actually asked for them) vs making N separate calls to CostFunction::Evaluate().

**Comment by spinicist** [comment]
Yes, my problem is dense. Do you have an example of the CostFunction you describe? The ones I found in the Tutorial all seem to output a 1x1 residual block. Sorry if I missed one.

**Comment by alexsmac** [comment]
The [ellipse_approximation example has a CostFunction which has two residuals](https://github.com/ceres-solver/ceres-solver/blob/master/examples/ellipse_approximation.cc#L272), which, assuming that you're not using auto-diff, which it sounds like you aren't, should show you what to do, note [these lines](https://github.com/ceres-solver/ceres-solver/blob/master/examples/ellipse_approximation.cc#L278) which set the number of residuals generated, and the number of parameter blocks expected, and the size of each expected parameter block.  You are responsible for calling these methods upon construction s/t the solver can interrogate how to invoke the CostFunction as detailed [here](http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres12CostFunctionE).  The required indexing for setting the outputs from Evaluate() is specified [here](http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres12CostFunction8EvaluateEPPCdPdPPd).

**Comment by spinicist** [comment]
Great, I will give it a try. Many thanks.

**Comment by sandwichmaker** [comment]
Going to close this, as there is no plan to work on this anytime soon.
