### ISSUE TITLE
Crash in ceres::Solve when called in omp parallel region

### ISSUE THREAD

**Issue by markusjrmueller** [ceres-solver/ceres-solver#184]
If the the solver options will be set to num_threads=1
but the ceres::Solve call will be called in an openmp parall region num threads > 1
the code crahes in program_evaluator.h 
when accessign the block_resdiuals
via 
"EvaluatePreparer\* preparer = &evaluate_preparers_[thread_id];"
and 
"EvaluateScratch\* scratch = &evaluate_scratch_[thread_id];"

The thread_id there is not 0 but 
BlockEvaluatePreparer\* BlockJacobianWriter::CreateEvaluatePreparers(int num_threads)
will be called with with num_threads = 1 before
so the preparers accessed in the code are not initialized

**Comment by sandwichmaker** [comment]
Thank you for the bug report. I will look at this shortly.

**Comment by sandwichmaker** [comment]
This is an interesting bug and one that permeates more than this file, because we use the same pattern everywhere in our OMP loops.  

#ifdef CERES_USE_OPENMP
      int thread_id = omp_get_thread_num();
#else
      int thread_id = 0;
#endif

We had been assuming that if the parallel region is initiated with num_threads = 1, 
omp_get_thread_num will always be zero, but apparently this is not the case?

are we using the wrong call here? because what we really want is the id of the worker that is being used by the loop parallelizer.

@keir what do you think? I will dig around in the OMP documentation in the interim.

**Comment by keir** [comment]
I am not sure what is going on here; I'll have to dig into it.

**Comment by sandwichmaker** [comment]
@markusjrmueller is this still a thing? just trying to figure out if this is actionable.

**Comment by sandwichmaker** [comment]
going to close it, if its still a thing, please re-open.
