### ISSUE TITLE
Use Eigen's Complete Orthogonal Decomposition instead of SVD for Covariance Computation

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#192]
Rasmus Larsen is in the process of contributing a COD implementation which would be substantially faster than the SVD based algorithm that we are using for covariance estimation.

**Comment by sweeneychris** [comment]
Is this referencing the code here? https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/covariance_impl.cc#L727

With Eigen 3.3 the COD is now available: http://eigen.tuxfamily.org/dox/classEigen_1_1CompleteOrthogonalDecomposition.html

This should only affect small dense problems, right? I might be able to take a stab at adding the COD class instead of SVD (for users with eigen 3.3 or higher) in the next few weeks.

**Comment by sandwichmaker** [comment]
yes, I'd be curious to see the time difference. Before doing a full implementation it would be worth benchmarking with a prototype on some matrices.

**Comment by sandwichmaker** [comment]
No plan on doing this anytime soon. Closing for now.
