### ISSUE TITLE
New warnings in gcc 6

### ISSUE THREAD

**Issue by jpgr87** [ceres-solver/ceres-solver#193]
Fedora rawhide just upgraded to gcc 6, and as a result the ceres-solver package [failed to build](https://bugzilla.redhat.com/show_bug.cgi?id=1307374) due to some new warnings (and the -Werror added to the CFLAGS in CMakeLists.txt)

If you look at the build.log in the attached bug, you'll see a few cases that look like the following:

```
/builddir/build/BUILD/ceres-solver-1.11.0/internal/ceres/rotation_test.cc:181:11: error: the compiler can assume that the address of 'arg' will never be NULL [-Werror=address]
   if (arg == NULL) {
       ~~~~^~~~
```

Upon further investigation, the calls handled by the four ```MATCHER```s that trigger the error are called with arguments allocated on the stack, and thus non-null.  gcc is now able to detect this, and issue a warning about the un-needed null check.

Having -Werror enabled in released code has been the source of much [bellyaching](https://blog.flameeyes.eu/2009/02/future-proof-your-code-dont-use-werror) over the years, mostly for this reason (new warnings appearing in new/different compilers.)  You may want to consider adding a CMake option to enable/disable ```-Werror``` so that development builds are stopped by -Werror but released builds aren't.

**Comment by sandwichmaker** [comment]
@keir what do you think?

**Comment by keir** [comment]
Thanks for the detailed investigation Rich. I think your suggestion to dial back -Werror for release builds makes sense. It's tricky since we do want to find and fix all of these warnings, but as you have noticed it's hard to fix these due to new warnings coming with new compilers.

Sameer & Alex, I support removing -Werror for release builds. What do you think?

**Comment by alexsmac** [comment]
I'm ambivalent, as we want to fix all warnings, having -Werror means when people test on new/different compilers to us they usually report any warnings that appear as they break the build, (as in fact has happened here :)).  If they are just warnings we probably wouldn't get any feedback about them.  That said, I totally understand the annoyance of users when it breaks just because of a new warning and we will (albeit with some delay from bleeding edge) find & fix all warnings that appear in any of our standard Clang (& GCC) toolchains.

I guess overall I'm OK with it - IMO we should probably just disable it completely, as Release is our default and Debug builds are so slow.  I'm assuming that this is what you mean, and not disabling it in the  official tagged release tarballs, but keeping it in master (for all CMAKE_BUILD_TYPE options)?  Doing the latter seems like it would be more unpredictable for users.
