### ISSUE TITLE
linker error of glog when using Ceres iOS build on Xcode 

### ISSUE THREAD

**Issue by mkstmyk** [ceres-solver/ceres-solver#196]
Hi,

I'm trying to make an iOS App using Ceres.
I have built Ceres1.11 for iOS (arm64) based on the instruction [here](http://ceres-solver.org/building.html#ios) by following command:
`cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake -DEIGEN_INCLUDE_DIR=/usr/local/include/eigen3 -DIOS_PLATFORM=OS ..`
As the result, libceres.a was successfuly obtained.

However, when I try to build an App on Xcode with the obtained library, I get several errors like below:
`Undefined symbols for architecture arm64:
  "google::base::CheckOpMessageBuilder::ForVar2()", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*) in optimization.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >* google::MakeCheckOpString<int, ceres::DimensionType>(int const&, ceres::DimensionType const&, char const*) in optimization.o`

This seems similar to [this case](https://github.com/ceres-solver/ceres-solver/issues/181), 
but I can' t solve the issue by same solution, just adding -lglog, because iOS build uses miniglog instead of glog, if I'm not mistaken.

Although there are no mentions about that in the official instruction (as far as I searched), do I have to build glog for iOS beforehand and add -lglog option in Xcode?
In that case, do I have to build Ceres with glog instead of miniglog?
In my understanding, when I use the option for cmake:
`-DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake`
cmake configures the makefile to use miniglog with returning following message:
`-- Building for iOS: Forcing use of miniglog instead of glog.`
How can I change it to original glog if it is really needed?

I appreciate if someone give me any advices or comments.
Thank you.

**Comment by alexsmac** [comment]
I think what is happening here is that you are not adding the complete contents of ${CERES_INCLUDE_DIRS} (as exported in CeresConfig.cmake) to your include path.  Specifically, when building with MINIGLOG enabled, there are two directories in ${CERES_INCLUDE_DIRS}:

1) The installed public headers for Ceres, which is basically a copy of the <Ceres source>/include/ceres directory (with a custom config.h).

2) The installed public headers for miniglog, which is a copy of the <Ceres source>/internal/miniglog directory, placed inside the installed Ceres header directory: <Install root>/include/ceres/internal/miniglog.

You must have: <Install root>/include/ceres/internal/miniglog on your path *before* /usr/local/include (if you have actual glog installed), as otherwise #include "glog/logging.h" will find: /usr/local/include/glog/logging.h, instead of <Install root>/include/ceres/internal/miniglog/glog/logging.h.  Which is what I think is happening in your case.

**Comment by mkstmyk** [comment]
Thank you alexsmac!
I could built my project on Xcode!
Your insight was right.

I had re-set up my include path on Xcode to the one for miniglog.
As I'm not using original glog, I just renamed it's directory so as to it will not be found, in case.

**Comment by alexsmac** [comment]
Great!
