### ISSUE TITLE
OpenMP Support on Mac

### ISSUE THREAD

**Issue by bbysmith91** [ceres-solver/ceres-solver#214]
Hello, newbie here
After installing ceres solver as a dependency for Theia SfM on Mac OS X, I learned that my build of Ceres Solver does not support OpenMP. Sorry for my inexperienced question, but why does Ceres Solver continue to disable OpenMP even though clang is supposed to support it? Is it just a Mac thing? Is there a workaround?
Thank you very much.

**Comment by alexsmac** [comment]
Clang's support for OpenMP was only merged into master (and enabled by default) relatively recently.  As such, the builds of Clang in Xcode >= 7 do not yet support OpenMP.  Hopefully this will be fixed in Xcode 8 coming later this year.

You can experiment with clang-omp from Homebrew if you want to experiment with OpenMP support on OS X.  It does work (Ceres built with it will be multithreaded), although you will have to build your projects that use Ceres with clang-omp as well otherwise you will likely see some undefined behaviour, usually resulting in segfaults.  I would only recommend trying this if you are feeling dedicated though: http://stackoverflow.com/questions/33668323/clang-omp-in-xcode-under-el-capitan

**Comment by bbysmith91** [comment]
Thanks! I will tinker around and see if it works somehow.
