### ISSUE TITLE
cubic_interpolation_test failing on i386

### ISSUE THREAD

**Issue by debalance** [ceres-solver/ceres-solver#221]
cubic_interpolation_test is failing on Debian's i386 and kfreebsd-i386 ports,
build logs are available here:
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=i386&ver=1.11.0%2Bgit20160903-1&stamp=1472996344
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=kfreebsd-i386&ver=1.11.0%2Bgit20160903-1&stamp=1472996844

**Comment by debalance** [comment]
Most likely same reason as in #212.

**Comment by sandwichmaker** [comment]
@debalance thanks for reporting. One of them is the same issue, the cubic_interpolation test failing. The other gradient_checker_test seems like an easier fix since it is using an exact equality check, which is never a good idea.

@dgossow can you look into this and the use of isApprox in that test? they should all be changed to ExpectClose or IsClose ?

**Comment by sandwichmaker** [comment]
I am going to file another bug, which is about gradient checker based on your logs. and mark this one duplicate

**Comment by sandwichmaker** [comment]
Filed https://github.com/ceres-solver/ceres-solver/issues/223 to address gradient_checker_test.
So closing this one.
