### ISSUE TITLE
error: ‘CERES_GFLAGS_NAMESPACE’ has not been declared

### ISSUE THREAD

**Issue by ramanpreet9** [ceres-solver/ceres-solver#241]
I am trying to run powell.cc  example. My cmake file is:
cmake_minimum_required(VERSION 2.8)
project(helloworld)
find_package(Ceres REQUIRED)
include_directories(${CERES_INCLUDE_DIRS})
add_executable(powell powell.cc)
target_link_libraries(powell ceres ${GFLAGS_LIBRARIES})

I also printed out the included directories:
 Found required Ceres dependency: Eigen version 3.2.0 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/local/include
-- Found Ceres version: 1.12.0 installed in: /usr/local with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, OpenMP]
-- dir='/usr/local/include'
-- dir='/usr/include/eigen3'
-- dir='/usr/local/include'

I think there might be an issue with gflags that i cant pinpoint here. I installed gflags per the given directions, but perhaps its not being included here?

**Comment by sandwichmaker** [comment]
It doesn't look like that you are searching for gflags.

**Comment by ramanpreet9** [comment]
I also added 
include_directories(${GFLAGS_LIBRARIES})

to my cmakelists.txt  but it doesnt help.

**Comment by alexsmac** [comment]
1) Without a call to find_package(), the gflags variables (GFLAGS_INCLUDE_DIRS & GFLAGS_LIBRARIES) will not be defined.  If you are using glog, and it was compiled against gflags then gflags should actually already be a public dependency of Ceres (as glog #includes gflags/gflags.h).  In fact, a bug to this effect just got fixed in master (and is in 1.12 RC3), previously we were not correctly capturing this, although if everything was built as a shared library it was implicit.

Best practice is to always call find_package() for any library that you *directly* use, so as the powell example directly #includes gflags, you should call find_package() for it in your CMakeLists.  As there is not a default find script for gflags in CMake, the fastest approach will be to copy Ceres' FindGflags.cmake into your own project - conventionally into a directory called 'cmake' at the top level of the source tree and add this line:

list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")

after your project(helloworld) declaration.  This will mean that when you call:

find_package(Gflags REQUIRED)

it will correctly detect and use the copied <SOURCE_DIR>/cmake/FindGflags.cmake script.  Once find_package(Gflags REQUIRED) has completed, if successful GFLAGS_INCLUDE_DIRS, GFLAGS_LIBRARIES & GFLAGS_NAMESPACE will all be defined.

The reason for this: CERES_GFLAGS_NAMESPACE, which is expanded automatically in Ceres by this line in the main CMakeLists.txt

add_definitions(-DCERES_GFLAGS_NAMESPACE=${GFLAGS_NAMESPACE})

is because gflags went through a brief period of existential angst and their top-level namespace changed, so in some versions it's google, in others it's gflags, Ceres has to be able to handle both hence we use a #define here, you could either do the same thing or just assume it's gflags as you are above which is generally going to be fine.

2) In CMake <Foo/FOO>_INCLUDE_DIRS contain the list of include directories for Foo, which should be passed to include_directories(), so this: include_directories(${CERES_INCLUDE_DIRS}) is correct.

3) <Foo/FOO>_LIBRARIES contain the list of libraries ([or imported CMake targets](http://ceres-solver.org/building.html#understanding-the-cmake-package-system)) that should be linked against to link against Foo, and should be passed to target_link_libraries(), *not* include_directories().  So this: include_directories(${GFLAGS_LIBRARIES}) is wrong.  The gflags libraries are already being linked against here: target_link_libraries(powell ceres ${GFLAGS_LIBRARIES})

4) For external projects (i.e. not part of the Ceres code tree) you should use: ${CERES_LIBRARIES}, not just ceres in target_link_libraries(), as detailed [here](http://ceres-solver.org/building.html#using-ceres-with-cmake).

**Comment by ZhengPan2014** [comment]
yes, just replace line 102 in powell.cpp with

gflags::ParseCommandLineFlags(&argc, &argv, true);

without any changing in CMakeLists.txt. 
ps: my CMakeLists.txt is as follow:

cmake_minimum_required(VERSION 2.8)

project(helloworld)

find_package(Ceres REQUIRED)
include_directories(${CERES_INCLUDE_DIRS})

# helloworld
add_executable(helloworld src/helloworld.cpp)
target_link_libraries(helloworld ${CERES_LIBRARIES})

# powell
add_executable(powell src/powell.cpp)
target_link_libraries(powell ${CERES_LIBRARIES})

**Comment by ZhengPan2014** [comment]
yes, just replace line 102 in powell.cpp with

gflags::ParseCommandLineFlags(&argc, &argv, true);

without any changing in CMakeLists.txt.
ps: my CMakeLists.txt is as follow:

cmake_minimum_required(VERSION 2.8)

project(helloworld)

find_package(Ceres REQUIRED)
include_directories(${CERES_INCLUDE_DIRS})
###helloworld

add_executable(helloworld src/helloworld.cpp)
target_link_libraries(helloworld ${CERES_LIBRARIES})
###powell

add_executable(powell src/powell.cpp)
target_link_libraries(powell ${CERES_LIBRARIES})
