### ISSUE TITLE
FindEigen.cmake cannot find eigen by default in Windows 10 

### ISSUE THREAD

**Issue by jasjuang** [ceres-solver/ceres-solver#249]
I downloaded the latest Eigen 3.3.1 from [here](http://eigen.tuxfamily.org/index.php?title=Main_Page) and go through the standard using cmake to generate the sln, and build the entire sln, and build the INSTALL project and all the eigen headers got installed to C:\Program Files (x86)\Eigen3

After that I clone the ceres repository, and run cmake I got the error "Failed to find Eigen". Even though I am able to use the cmake-gui to specify the directory and get pass this, I think the FindEigen.cmake should have the capability to recognize the default INSTALL location of eigen.

**Comment by alexsmac** [comment]
[This](https://bitbucket.org/eigen/eigen/pull-requests/214/fix-eigen3configcmake-install-logic-in/diff) which got merged into Eigen >= 3.3 [here](https://bitbucket.org/eigen/eigen/commits/e90d2e4b30054d7) is the issue, as the default install location on windows is C:/Program Files/<PROJECT_NAME>, so changing the project name breaks detection.

This (and #250) should be fixed by this CL: https://ceres-solver-review.googlesource.com/9300 - please can you test if it fixes the issues for you?

**Comment by alexsmac** [comment]
This has just been merged into master, but please test that it works for you there.

**Comment by jasjuang** [comment]
This solves it for me, thanks!

**Comment by jasjuang** [comment]
Commit 74df65b breaks this. Now when I did a fresh pull of ceres with the same Eigen setup, I got the below error 

``````
-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
-- Found installed version of Eigen: C:/dev/eigen/build
CMake Error at cmake/FindEigen.cmake:89 (message):
  Failed to find Eigen - Could not find file:
  C://include/eigen3/Eigen/src/Core/util/Macros.h containing version
  information in Eigen install located at: C://include/eigen3.
Call Stack (most recent call first):
  cmake/FindEigen.cmake:171 (eigen_report_not_found)
  CMakeLists.txt:206 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/dev/ceres-solver/build/CMakeFiles/CMakeOutput.log".

C:\dev\ceres-solver\build>
``````

I have no idea why and how it points back to my source Eigen build folder instead of pointing to the installed version at `C:\Program Files`. I looked into the new FindEigen.cmake and I suspect it's line 119
`find_package(Eigen3 QUIET)` breaking it, but I cannot find a corresponding FindEigen3.cmake that goes with the find_package hence I cannot debug further. Can you please look into this?

**Comment by alexsmac** [comment]
This looks like an issue with Eigen's CMake, it implies that find_package(Eigen) is reporting that:

EIGEN_INCLUDE_DIR=C://include/eigen3

The most likely explanation for this mangled path is that the windows-specific logic for determining the installed header location from the Eigen3Config.cmake path is incorrect.  On *nix where it installs to /usr/local/share/eigen3/cmake (on 3.3.1), the relative path: '../../../include/eigen3' will navigate from the Eigen3Config.cmake install path to the Eigen header install path, on windows this clearly isn't the case.

There are a number of fixes that have gone into Eigen's CMake configuration to fix windows install paths since late 2015.

This:
```
-- Found installed version of Eigen: C:/dev/eigen/build
```
implies that Eigen has exported its build directory into the CMake package registry, which is then being detected by CMake, albeit the configured Eigen3Config.cmake that is in the build directory is expecting to be installed, and has the correct relative paths for installation, but not for export.

This is probably in part caused by the fact that CMake and the CMake GUI result in different package search preferences on windows than on any other OS.  In Ceres we explicitly re-order the searches for gflags & glog to make the behaviour more consistent.  I have [added a CL here](https://ceres-solver-review.googlesource.com/#/c/10380/) that does the same for Eigen - please try it and see if it fixes your problem.

You should also be able to resolve this by specifying explicitly Eigen3_DIR in CMake when configuring Ceres to point to the directory containing the installed Eigen3Config.cmake.

**Comment by jasjuang** [comment]
@alexsmac I tried the CL and I get `endif An ENDIF command was found outside of a proper IF ENDIF structure.` I noticed that from line 153~179. There are 4 3 ifs and 4 endifs.

**Comment by alexsmac** [comment]
I can't replicate this, and the statements appear to be fine.  Are you applying the CL on top of the latest master branch?

**Comment by jasjuang** [comment]
@alexsmac Sorry I missed one line to add in your CL. I added it back and everything is working great. Look forward to see the merge.

**Comment by alexsmac** [comment]
This has now been merged into master.

**Comment by adityargupta** [comment]
Just downloaded the latest version of ceres 1.14 and eigen 3.3.4 and I am getting the same error above:

CMake Error at cmake/FindEigen.cmake:89 (message):
  Failed to find Eigen - Could not find file:
  C:/Users/agupta/Documents/EIS/include/eigen3/Eigen/src/Core/util/Macros.h
  containing version information in Eigen install located at:
  C:/Users/agupta/Documents/EIS/include/eigen3.
Call Stack (most recent call first):
  cmake/FindEigen.cmake:219 (eigen_report_not_found)
  CMakeLists.txt:212 (find_package)

I looked into FindEigen.cmake and the above changes you suggest are in the file. In spite of updating the paths in CMake Gui it still tries to look in C:/Users/agupta/Documents/EIS/include/eigen3. Any help will be appreciated. Thanks.

**Comment by jasjuang** [comment]
@adityargupta I suggest you install ceres through [vcpkg](https://github.com/Microsoft/vcpkg/) on windows. It simplifies the installation to `vcpkg install ceres`

**Comment by valterbenedetto** [comment]
unbelievable!

**Comment by valterbenedetto** [comment]
Got the same issues (both with Eingen, Ceres and Colmap ) and lost a lot of time to solve.
