### ISSUE TITLE
FindSuiteSparse doesn't work right on OS X

### ISSUE THREAD

**Issue by ivan-ushakov** [ceres-solver/ceres-solver#257]
I have SuiteSparse installed on my system.

    $ ls /usr/local/include/suitesparse/amd.h
    /usr/local/include/suitesparse/amd.h

When I run cmake I see this error:

    -- Failed to find SuiteSparse - Did not find AMD header (required SuiteSparse component).

But that path presented in list:

    list(APPEND SUITESPARSE_CHECK_INCLUDE_DIRS
      ${SUITESPARSE_INCLUDE_DIR_HINTS}
      /opt/local/include
      /opt/local/include/ufsparse # Mac OS X
      /usr/local/homebrew/include # Mac OS X
      /usr/local/include
      /usr/local/include/suitesparse
      /usr/include/suitesparse # Ubuntu
      /usr/include)

**Comment by alexsmac** [comment]
Usually this is caused by a broken symlink.  As you're on OS X and assuming that you are using Homebrew, then: /usr/local/include/suitesparse/amd.h is probably a symlink to somewhere in the Cellar.  Does the file the symlink is pointing to exist?  If it doesn't (has been moved/deleted) then CMake's find_path function will report it as not found.

This is only way I can imagine this failing, as I can't replicate the issue on my OS X build machines except via a bad symlink.

**Comment by ivan-ushakov** [comment]
Sorry, I forgot to tell that I'm building for iOS. Here is my cmake command:

    cmake \
    -DCMAKE_TOOLCHAIN_FILE=<some path>/ceres-solver/cmake/iOS.cmake \
    -DEIGEN_INCLUDE_DIR=<some path>/eigen \
    -DIOS_PLATFORM=OS \
    <some path>/ceres-solver

I also modified CMakeLists.txt and turned on Sparse:

    message(STATUS "Building for iOS: Forcing use of miniglog instead of glog.")
    update_cache_variable(SUITESPARSE ON)

**Comment by alexsmac** [comment]
OK, so your problem are these lines from ceres-solver/cmake/iOS.cmake:

```
# Set the find root to the iOS developer roots and to user defined paths.
set(CMAKE_FIND_ROOT_PATH ${CMAKE_IOS_DEVELOPER_ROOT} ${CMAKE_OSX_SYSROOT}
  ${CMAKE_PREFIX_PATH} CACHE string  "iOS find search path root" FORCE)
...
# Only search the specified iOS SDK, not the remainder of the host filesystem.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

which force find_package/library/path() to search only those paths which are either within the iOS developer root directory, or in the list explicitly specified in CMAKE_PREFIX_PATH by the user irrespective of how those functions are invoked.

This is intentional, as libraries built for the host OS should not be assumed to be compatible with an iOS (ARM) platform.

Whilst it may be possible to compile SuiteSparse for iOS (certainly there are [some old examples of people having done so](https://github.com/egoist-sx/Optimization_Toolkit_iOS/tree/master/SuiteSparse)) given the compiler optimisation flags that SuiteSparse employs, I would not expect a version built for OS X (as anything installed in /usr/local should be) to be compatible.  However, if you had a version that was built for iOS, setting CMAKE_PREFIX_PATH should allow you to add it to the search paths s/t it will be found.

You should also note that Apple's policy previously was that various BLAS calls (e.g. dsyrk_()) were private APIs, and any application built using them would not be allowed in the app store.  Which is why we explicitly disable LAPACK and SuiteSparse (which requires LAPACK) when building for iOS.  I would verify whether this policy has changed before pursuing this any further.

Finally, you should be able to use the EIGEN_SPARSE option in Ceres (which makes Ceres LGPL) for solving sparse systems on iOS without requiring SuiteSparse.

**Comment by ivan-ushakov** [comment]
Thank you for this details, now it is clear why cmake ignored my parameters. About `EIGEN_SPARSE` option - I tried with it and without it but time result is the same (I checked on `simple_bundle_adjuster.cc` and `problem-16-22106-pre.txt` as input). Also I tried with BLAS from Accelerate.framework and without with same result.
I guess that `SUITESPARSE` option will not change this or I'm wrong?

**Comment by alexsmac** [comment]
YMMV, it depends on the structure of the problem you are trying to solve, if the problem is essentially dense then SuiteSparse, or indeed any sparse linear algebra library is unlikely to make anything faster, and may (as noted in the comments in simple_bundle_adjuster) make things slower.

Note that if you are using simple_bundle_adjuster.cc that you need to set *both* [linear_solver_type](http://ceres-solver.org/nnls_solving.html#_CPPv2N6Solver7Options18linear_solver_typeE) to actually force the use of a sparse linear algebra library as well as [sparse_linear_algebra_library_type](http://ceres-solver.org/nnls_solving.html#_CPPv2N6Solver7Options34sparse_linear_algebra_library_typeE) to control which is used.  By default simple_bundle_adjuster uses linear_solver_type = ceres::DENSE_SCHUR so no dense library will be used.

**Comment by ivan-ushakov** [comment]
May I use `ceres::SPARSE_NORMAL_CHOLESKY` with `EIGEN_SPARSE`? Sorry for this offtopic.

**Comment by alexsmac** [comment]
Yes, in fact without specifying ceres::SPARSE_NORMAL_CHOLESKY no sparse library will be used.  If you specify SPARSE_NORMAL_CHOLESKY Ceres will select as the default the 'best' sparse linear algebra library from the set it was compiled with.

**Comment by ivan-ushakov** [comment]
Ok, than you for your answers. Feel free to close this issue because not I know why it was happen.
