### ISSUE TITLE
Unable to build ceres-solver for iOS with c/c++ flag `-fembed-bitcode`

### ISSUE THREAD

**Issue by AndreasSchacherbauer** [ceres-solver/ceres-solver#282]
Hi,
I tried to build ceres for iOS with the bitcode option enabled but I got the following error: `clang: error: -mllvm is not supported with -fembed-bitcode`.
I had to remove the `-mllvm` cxx flag in the main [CMakeLists.txt](https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L702) file and was then able to specify `-fembed-bitcode` in the iOS.cmake toolchain file line 250-255.

For what is the `-mllvm` option needed or is there another way to resolve my bitcode build error?

**Comment by alexsmac** [comment]
The ``-mllvm`` option is required to pass the ``-inline-threshold=600`` option through Clang to the LLVM pipeline.  As per the comment in the CMakeLists, historically we have found that increasing the inlining threshold on Clang made a big performance improvement overall as otherwise Eigen was being hobbled as various functions were not being inlined.

As it seems from the Clang/LLVM code that -mllvm and -fembed-bitcode are incompatible options, I don't think that there is a workaround here other than removing the ``-mllvm -inline-threshold=600``, however that would impact performance.

**Comment by sandwichmaker** [comment]
@alexsmac it maybe worth looking at the -inline-threshold again. Its been a while since we evaluated the need for it.

**Comment by sandwichmaker** [comment]
A quick informal test on my laptop does not indicate that this is particularly useful.  
@alexsmac do you remember what prompted this inline threshold to begin with?

**Comment by sandwichmaker** [comment]
So this seems to be the CL that added this 

https://github.com/ceres-solver/ceres-solver/commit/3d6eceb45cf27024865908f0c10a5c2b0f8719cf

so I need to check as to what happens to the performance of ITERATIVE_SCHUR with and without this.

**Comment by alexsmac** [comment]
I think it was something @keir added to improve Jet performance, without it I think autodiff cost functions were being clobbered when evaluating Jets with larger parameter sizes.

**Comment by sandwichmaker** [comment]
Turns out this has to do with the Schur based solvers rather than Jets. And there is a performance differential, but I need to spend some time to see if we can do this via compiler annotations instead of compiler flags.

**Comment by abaldacci** [comment]
Hi, 

any updates on this problem?

Thanks

**Comment by sandwichmaker** [comment]
@abaldacci you can just remove the mllvm option from the cmake file and it should work no?

**Comment by sergiud** [comment]
Is enabling the option from e0fef6ef05c580c40d6293749d8f88904d140c8d maybe sufficient?

**Comment by sandwichmaker** [comment]
Yes this should be done now, you should be able to use the cmake file to do this.
