### ISSUE TITLE
Suggestion: Continuous Integration

### ISSUE THREAD

**Issue by jasjuang** [ceres-solver/ceres-solver#295]
Is it possible to add continuous integration into ceres? So whenever there is a build compilation error it will get caught automatically. I am wondering whether Google is using any CI internally for ceres. If not, I suggest Travis CI for linux compilation and AppVeyor for windows compilation. Both are free for open source projects.

**Comment by alexsmac** [comment]
I did set up Travis CI for Ceres a while back here, although I didn't get around to merging it, I will have another look at it.  Internally to Google there is CI for Ceres, although none of the Ceres maintainers use Windows so we don't have anything set up for that - AppVeyor looks great for this though, have you used it before?

**Comment by jasjuang** [comment]
@alexsmac My experience is mainly using AWS + Jenkins for CI with both Linux and Windows. It's more painful to setup but cost-wise is less for private repos. Another open source library [caffe](https://github.com/BVLC/caffe/) which I used has AppVeyor integrated, and the setup file looks fairly straight forward so I believe it won't be too hard to setup.

**Comment by sandwichmaker** [comment]
@jasjuang can you try https://ceres-solver-review.googlesource.com/#/c/10460/ and tell me if it works for you?

**Comment by bjornpiltz** [comment]
I have set up AppVeyor integration over at https://github.com/bjornpiltz/ceres-solver. It is very straight forward. Apart from adding [appveyor.yml](https://github.com/bjornpiltz/ceres-solver/blob/master/appveyor.yml) I needed to make [one change to CMakeLists.txt](https://github.com/ceres-solver/ceres-solver/commit/040b445e94739ec93a12633cd1bfa6844ca670bb) to enable the use of [jlblancoc's SuiteSparse](https://github.com/jlblancoc/suitesparse-metis-for-windows)(A temporary hack for sure). I set up another repo to build the dependencies here: https://github.com/bjornpiltz/ceres_msvc_deps.

Every new commit to master triggers builds at [AppVeyor](https://ci.appveyor.com/project/bjornpiltz/ceres-solver), which in turn publishes binaries to [the release page](https://github.com/bjornpiltz/ceres-solver/releases) 

I would be happy to contribute any of those scripts to Ceres.

PS: The MSVC_2015_x86 build fails because of an Appveyor time limit of 60 minutes per build on the free plan.

**Comment by sandwichmaker** [comment]
Thanks @bjornpiltz this is awsome. @alexsmac could you work with @bjornpiltz to see the best way to integrate this into cmake?

**Comment by alexsmac** [comment]
Interesting, so I don't have a Windows machine but I'm slightly surprised that [jlblancoc's SuiteSparse](https://github.com/jlblancoc/suitesparse-metis-for-windows) is actually working for you when used as above.

Using this:

```
find_package(SuiteSparse CONFIG REQUIRED)
```

forces the use of the configured suitesparse-config.cmake installed by CMake, which bypasses the `FindSuiteSparse.cmake` that ships with [jlblancoc's SuiteSparse](https://github.com/jlblancoc/suitesparse-metis-for-windows) in which case `SuiteSparse_USE_LAPACK_BLAS` is ignored.  In that case, the only way LAPACK is brought in is via [this line](https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/cmake/SuiteSparse-config-install.cmake.in#L8), which I would expect to fail with output like this: `-- Could NOT find LAPACK (missing: LAPACK_DIR)` when `find_package(SuiteSparse CONFIG REQUIRED)` is run, as it will just fall back to the standard FindLAPACK.cmake script that ships with CMake that works with Linux / OS X, but typically not with Windows.  However, is this what [these lines](https://github.com/bjornpiltz/ceres-solver/blob/master/appveyor.yml#L24) in your appveyor.xml are there to fix by copying the BLAS/LAPACK libraries into a default install location?  My other thought is that this *might* be working if SuiteSparse were compiled statically.

There is of course another 'feature' of Windows using a case-insensitive filesystem - namely that the above wouldn't actually find SuiteSparse on a case sensitive OS.  The problem is that [jlblancoc's SuiteSparse](https://github.com/jlblancoc/suitesparse-metis-for-windows) is actually exporting itself as `suitesparse` - that's fine, although it means that the following are actually what should be used to find/check for detection on case-sensitive OSs:

```
find_package(suitesparse)
if (suitesparse_FOUND)
   message("Found SuiteSparse")
endif()
```

I think the best way to import this would be to update our FindSuiteSparse.cmake script in the same manner that we have done for glog & gflags where it can optionally use an external provider to find SuiteSparse and then wrap the output into the expected variables (e.g. setting SUITESPARSE_FOUND).  As its a private link dependency, we shouldn't have to do anything in CeresConfig.cmake.

However, I would like to get to the bottom of what exactly is going on with BLAS & LAPACK.

**Comment by sandwichmaker** [comment]
Is this actionable? if so, @jasjuang or @alexsmac will you take this on?

**Comment by alexsmac** [comment]
Ceres is now building on [Travis CI](https://travis-ci.org/ceres-solver/ceres-solver), we can have another look at getting the Windows build on AppVeyor integrated too.

**Comment by nocnokneo** [comment]
It makes me sad that this is still not implemented. For a large, highly-configurable, multi-platform code base, it's so inefficient to not have automatic CI builds that _enforce_ that every Gerrit CL successfully run all tests on at least some minimal combination of supported platforms and configurations.

**Comment by sandwichmaker** [comment]
Taylor send us a pr!

**Comment by nocnokneo** [comment]
Huh? Are GitHub PRs the new workflow now? That would make things actually possible to implement in a PR patch (plus some funding from Google for AppVeyor minutes probably). Even better would be GitLab MRs. That could be done with a `.gitlab-ci.yml`. But from what I understand, Gerrit is the only allowed review/integration workflow. I don't know specifics on how that would need to be setup except that it is not something that works out of the box and is beyond the scope of a patch from a community contributor.

**Comment by sandwichmaker** [comment]
I meant a pr on GitHub.
I am thinking about moving from gerrit to github but I need to figure out
the google CLA workflow on GitHub.

**Comment by sergiud** [comment]
Ceres Solver added Github workflows for all major platforms. I guess the issue can be closed now.
