### ISSUE TITLE
Ceres solver 1.13.0 C++11 option

### ISSUE THREAD

**Issue by huangqinjin** [ceres-solver/ceres-solver#306]
Ceres solver 1.13.0 uses `target_compile_features` to specify C++11 requirements, but the generated compiler options is `-std=gnu++11` instead of `-std=c++11` on Ubuntu 16.04. `find_package(Ceres)` does not report something like 1.12.0
```
-- Ceres version 1.12.0 detected here: /usr/local was built with C++11. Ceres target will add C++11 flags to compile options for targets using it.
```

**Comment by sandwichmaker** [comment]
@alexsmac

**Comment by alexsmac** [comment]
This should be resolved by [this CL](https://ceres-solver-review.googlesource.com/#/c/ceres-solver/+/10900) which is out for review.

**Comment by huangqinjin** [comment]
But 1.12.0 uses `-std=c++11` and 1.13.0 uses `-std=gnu++11` by default, right?

**Comment by alexsmac** [comment]
@huangqinjin, on newer versions of CMake (>= 3.1), Ceres now specifies the C++11 features that it requires via target_compile_features() rather than forcing the specific compiler flag to -std=c++11.  CMake will then pick the 'best' compiler flag that satisfies all of the specified features for a target that depends on Ceres, so if that target specified different features to Ceres, CMake will choose a compiler flag that satisfies the superset.  By default on GCC, CMake will (from memory) choose the least restrictive option, which is -std=gnu++ but that choice is determined by CMake.

This is required to support clients of Ceres requiring C++14/17 in their code, in which case Ceres should not attempt to force the flag back to C++11.

**Comment by sandwichmaker** [comment]
CL has been submitted. Thank @alexsmac
