### ISSUE TITLE
support RelWithDebInfo

### ISSUE THREAD

**Issue by v01d** [ceres-solver/ceres-solver#376]
Hi,
when building ceres with CMAKE_BUILD_TYPE=RelWithDebInfo, optimization flags that are set for Release (-march=native) are not set. This target should be Release + "-g" flag, so that it is possible to follow backtraces and still use optimized code. On building ceres as part of a ROS Catkin workspace, this is particularly troublesome as it is not designed to mix build types and forces me to have everything on Debug or Release.

I suspect it is a matter of extending the test of this variable to RelWithDebInfo and set the apropriate flags. In fact, I believe that the handling of CMAKE_CXX_FLAGS flags variable is not entirely correct, as this variable should not be touched to specify a configuration, but the specific CMAKE_CXX_FLAGS_<BUILD_TYPE> (which will be used by cmake automatically).

**Comment by richmattes** [comment]
Maybe consider adding an option to enable native optimization?  For tasks like distribution packaging, you don't necessarily want native optimizations as the optimizations will be native to the build machine, not the client machines.  Distributions also tend to use RelWithDebInfo during the build so that debug info is generated to populate -dbg packages.

**Comment by alexsmac** [comment]
This should now be updated in master, `-march=native` is no longer enabled by default on Linux (it was not enabled by default on OS X) and the docs have been updated to explain how to add it should they wish to do so.
