### ISSUE TITLE
Analytic CostFunction Jacobians wrt local parametrization

### ISSUE THREAD

**Issue by artivis** [ceres-solver/ceres-solver#387]
I have the feeling that this topic has been raised a couple times yet I couldn't find a satisfactory answer...
So here we are again,

I'm trying to take benefit from a piece of code that defines some basics operations on manifolds (e.g. SO2/3) together with the Jacobians. No suspense here, all Jacs are developed wrt the tangent space.

For short  
```
R : group element (e.g. S3),
r : vector of representation of group element (e.g. quaternion )
y = f(R) an operation on manifold

cost function -> `d y / d r`
local param -> `d r / d R`
Ceres internally does -> `d y / d R = d y / d r . d r / d R`
```
So what do I do with 'my' `d y / d R` ??

As of now the trick of setting the local param Jac to identity while the user-provided Jac is stashed to the cost function Jac together with some Zero columns seems to work (similarly to https://github.com/ceres-solver/ceres-solver/issues/303) but that does feel hacky.

```
cost function -> `[d y / d R, 0]`
local param -> `I`
Ceres internally does -> `d y / d R = [d y / d R, 0] . I`
```

As I understand there are no proper way to input these Jacs, maybe you can point me to another less-hacky solution ??

Any chance ceres will provide at some point a clean API for it ?? (maybe a new `CostFunction` class ?)

Manifold manipulation has been trendy lately in robotics (see TRO-2017 best paper award) and ceres is one of the few well implanted solver in that field too. Maybe those guys should meet ?

In any case, thanks for your efforts !

PS - One should be careful with his documentation :DD
`5. You love the chain rule and actually enjoy doing all the algebra by hand.`

**Comment by sandwichmaker** [comment]
@artivis 

I understand the appeal of working on the manifold and respecting its local tangent space and ceres is hip to all the latest hotness there. It just prefers to compose the action of a CostFunction with the LocalParameterization. There are a number of reasons for this.

1.  Purely historically CostFunctions came first and LocalParameterizations came much later. So CostFunctions were always expected to operate on parameter blocks, and then their Jacobians were composed with the Jacobian of the local parameterization.

2. Number of people asking to compute derivatives is quite small. In part because the autodiff works in parameter blocks and getting derivatives right is enough trouble, that it is simpler to just compose the two objects rather than trying to implement everything together.

3. The performance impact seems fairly minimal, and mathematically things are exactly the same. So it is not clear why we should expand the API surface.

**Comment by sandwichmaker** [comment]
@artivis I am going to close this issue. If you have further questions on this issue, feel free to re-open or discuss on the mailinglist.

**Comment by v01d** [comment]
Hi,
I just asked a question on the mailing list relevant to this thread. In my email I asked about an approach for avoiding the intermediate jacobian as suggested in #303. This approach works, however it feels hacky and, in fact, I cannot use the gradient checker since the numerically computed jacobian computes a different jacobian than mine, of course.

So, since this has been asked a few times, I wonder if it would be possible to allow for an option to mark a given cost function as computing the jacobian already in the local space and, thus, not post-multiply it by the jacobian of the parametrization. This would involve either expecting a differently sized jacobian (residual x local size instead residual x global size) or maybe even have ceres grab the first "local size" columns of the matrix with "global size" columns (where the remainder would always be zeros).

To me is not that much of a matter of efficiency but something that forces the user the derive jacobians which are not commonly derived. As mentioned by the other user, most papers derive w.r.t. the local parameters and we can directly implement them this way. Of course I suspect that, in some cases, there could be some performance (or maybe even a numerical) difference but I'm not really interested in that since I suspect it would be small.

What do you think about the change? To me it seems isolated enough.
