### ISSUE TITLE
Missing lapack dependency to libf2c

### ISSUE THREAD

**Issue by allo-** [ceres-solver/ceres-solver#390]
When building (for windows) with lapack, ceres links against ``lapack.lib``, but not against ``libf2c.lib``, what causes unresolved symbol errors when linking a project against ceres.

**Comment by alexsmac** [comment]
This looks like a bug in the FindLAPACK.cmake shipped with CMake, it should be pulling in all libraries required to link against LAPACK, but evidently [Eigen (amongst others)](https://bitbucket.org/eigen/eigen/src/7a835107faf8b928ed3ccca591ceded3e008aebb/cmake/FindLAPACK.cmake?at=default&fileviewer=file-view-default#FindLAPACK.cmake-84) have their own forks that have special cases for f2c for Windows.  I will have a look at a similar update for Ceres.

**Comment by sandwichmaker** [comment]
This is a bit complicated and not really Ceres or even FindLAPACK's fault. Allow me to explain.

The standard [LAPACK](http://www.netlib.org/lapack/) is in pure Fortran. Fortran 95 as I understand it. Building and using it requires a fortran compiler and no libf2c.

A number of libraries (including Eigen) that implement parts of LAPACK using their own optimized implementations say in C or C++ then have two choices. Have the remaining LAPACK being fortran and require two compilers, or use f2c to translate some of the fortran functions to C and stick to using one compiler.

Eigen does this. This has multiple problems. The part of LAPACK that ships with Eigen is not complete, it is missing large chunks of a full LAPACK distribution, but it is enough for most uses. The f2ced code is from an old version of LAPACK since f2c only works on FORTRAN77 or something like that. it is not compatible with newer versions of LAPACK.

Vendors like Intel when they ship an optimized BLAS + LAPACK, they ship a binary build with a C/C++ and a Fortran compiler so you do not have to worry about pulling in libf2c.

There is a similar issue with BLAS libraries, Complex level 2 blas functions, but that story is for another day.

So what you are seeing here is a combination fo compiler availability, old f2ced code etc.

**Comment by sandwichmaker** [comment]
@allo- it is not clear what Ceres can do here. This is a problem with the upstream library that is bringing in a libf2c dependency but not properly bringing it along.

**Comment by allo-** [comment]
I was not sure, where the bug lies. I thought about Suitesparse or clapack itself. So this is a cmake bug?

**Comment by sandwichmaker** [comment]
The bug lies in your lapack implementation, which should declare its dependency on libf2c.

**Comment by sandwichmaker** [comment]
@alexsmac is this something ceres can do anything about, or should we close this?

**Comment by alexsmac** [comment]
I don't think we should run modified versions of the default CMake FindBLAS/FindLAPACK packages which I think is where this issue lies, in that they should report all include directories/libraries required in order to use BLAS/LAPACK.
