### ISSUE TITLE
Problem in finding the path to shared library of ceres in ubuntu matlab mex

### ISSUE THREAD

**Issue by krishnakumarrs** [ceres-solver/ceres-solver#405]
I have tried to run a mex in matlab environment

Invalid MEX-file '/T/***.mexa64': libceres_shared.so.1.6.0: cannot open shared object file: No such file or
directory.

Please help.

**Comment by alexsmac** [comment]
Your MEX file was probably compiled against a very old version of Ceres that presumably no longer exists on your system.  Ceres hasn't built a library called `ceres_shared` since about 2014, since then Ceres will built both static & shared libraries as `libceres.a/so/dylib`.  You need to recompile your MEX file linking to the version of Ceres that you have installed.
