### ISSUE TITLE
A residual block object for each point in a point cloud or for each pixel?

### ISSUE THREAD

**Issue by dmitry-akimov-dXgjvQjNiMuVYecJ** [ceres-solver/ceres-solver#459]
The way in which the examples, e.g. `curve_fitting.cc`, `denoising.cc`, suggest that you need to write code with Ceres, namely, allocating two objects with virtual functions on the heap to store a single 2D point (2 doubles - 16 bytes, or 2 floats - 8 bytes) or a single pixel (3-4 bytes), raises the question about efficiency of such representation. Additionally, Ceres seems to insert the pointers to those objects into an `std::map` internally. Thus, the memory cost and the performance of adding the points or pixels are much worse than if they were added as a single memory block.

```c++
  for (int i = 0; i < kNumObservations; ++i) {
    problem.AddResidualBlock(
        new AutoDiffCostFunction<ExponentialResidual, 1, 1, 1>(
            new ExponentialResidual(data[2 * i], data[2 * i + 1])),
```

If I have a 2D point cloud (2 floats per point, 8 bytes) or an image (3 bytes per pixel) and want to fit a model into it with Ceres, is this really the way to go? Is there a better option, e.g. `ceres::DYNAMIC`, or maybe I am missing something that justifies the added cost?

**Comment by keir** [comment]
Whether it makes sense or not for you to use a single or multiple residuals depends on the relationship of variables in your problem. If your residuals are all coupled to all variables, then it makes sense to use a single residual block. However, if they are not, then getting Ceres to exploit the sparsity in your problem (due to not all cost functions depending on all variables) requires you to tell Ceres about the cost function to variable dependency, explicitly. CostFunctions (which tell Ceres how to compute cost and derivative) and ResidualBlocks (which tell Ceres which sets of variables match to which cost functions, thus the implied sparsity) are that mechanism.

One important benefit of the virtual function approach is that you can arbitrary mix and match cost functions. The examples you cite happen to use the same cost function for each residual, but in practice many real-world problems require many different types of constraints and variable dependencies. With Ceres, you are free to model the problem any way you please, including arbitrary variable coupling and cost functions. Ceres originated from the need for flexible least squares modeling, since custom-built solvers focused on a particular sparsity structure ultimately proved too limiting.

At various times in the past we've debated adding a mechanism for repeated cost function blocks with regular sparsity, but the cost/benefit never added up. If this is something you're interested in, let's chat!
