### ISSUE TITLE
Can't find gflags.h when building on Fedora

### ISSUE THREAD

**Issue by lukehutch** [ceres-solver/ceres-solver#491]
When building `ceres-solver` in Fedora 29, I see this:

```
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/lib64/cmake/gflags
-- Detected broken gflags install in: /usr/lib64/cmake/gflags, version: 2.1.2 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
-- Detected gflags version: 2.1.2
-- Failed to find gflags - Could not find file: //include/gflags/gflags.h containing namespace information in gflags install located at: //include.
-- Failed to find gflags - Failed to determine gflags namespace using regex for gflags version: 2.1.2 exported here: /usr/lib64/cmake/gflags using CMake.
-- Did not find Google Flags (gflags), Building without gflags - no tests or tools will be built!
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Glog: /usr/include  
-- Found Google Log (glog). Assuming glog was NOT built with gflags support as gflags was not found.  If glog was built with gflags, please set the gflags search locations such that it can be found by Ceres.  Otherwise, Ceres may fail to link due to missing gflags symbols.
```

The "//include" should be "/usr/include":

```
# rpm -ql gflags-devel 
/usr/include/gflags
/usr/include/gflags/gflags.h
/usr/include/gflags/gflags_completions.h
/usr/include/gflags/gflags_declare.h
/usr/include/gflags/gflags_gflags.h
/usr/lib64/cmake/gflags
/usr/lib64/cmake/gflags/gflags-config-version.cmake
/usr/lib64/cmake/gflags/gflags-config.cmake
/usr/lib64/cmake/gflags/gflags-export-noconfig.cmake
/usr/lib64/cmake/gflags/gflags-export.cmake
/usr/lib64/libgflags.so
/usr/lib64/libgflags_nothreads.so
/usr/share/doc/gflags-devel
/usr/share/doc/gflags-devel/designstyle.css
/usr/share/doc/gflags-devel/index.html
```

**Comment by sandwichmaker** [comment]
@alexsmac PTAL.

**Comment by alexsmac** [comment]
Interesting, but I think this is actually an issue with the gflags 2.1.2 install.  Looking at their [config.cmake.in file at version 2.1.2](https://github.com/gflags/gflags/blob/1a02f2851ee3d48d32d2c8f4d8f390a0bc25565c/cmake/config.cmake.in#L13), which should be configured into `/usr/lib64/cmake/gflags/gflags-config.cmake` in your case, `gflags_INCLUDE_DIR` is set based on the relative position of the installed file based on the installation prefix specified when it was built [here](https://github.com/gflags/gflags/blob/1a02f2851ee3d48d32d2c8f4d8f390a0bc25565c/CMakeLists.txt#L345).  My assumption would be that `gflags_INCLUDE_DIR` specified in `gflags-config.cmake` is wrong, specifically that it's just `//include` because the relative path adjustment is one level deeper than it should be, so `usr` is incorrectly removed.

You should be able to verify this by looking at `/usr/lib64/cmake/gflags/gflags-config.cmake` assuming that I'm correct, this looks like a packaging bug and not something that should be fixed in Ceres.

**Comment by lukehutch** [comment]
Well literally all of [`FindGflags.cmake`](https://github.com/ceres-solver/ceres-solver/blob/master/cmake/FindGflags.cmake) appears to be special case handling of the wide range of packaging differences and issues encountered in the wild. `FindGflags.cmake` seems to be aware of an issues with `gflags <= 2.12`, because it [says so](https://github.com/ceres-solver/ceres-solver/blob/master/cmake/FindGflags.cmake#L386). But it doesn't deal with the situation correctly, or solve the problem.

**Comment by alexsmac** [comment]
The specific issue with gflags versions <= 2.1.2 that is resolved by Ceres' FindGflags is linked in the output and has to do specifically with the names of the imported targets vs the name of the reported library in the `gflags_LIBRARIES` variable.  That issue affected all distributions and OSs.

Your issue appears to be that the Fedora gflags package was misconfigured when it was built so that the resulting package is not relocatable to the intended installation directory.  That issue is AFAIK Fedora-specific (I have not encountered this on any other Linux variant) and not a gflags bug but rather a user error.

You can verify the package is incorrect by inspecting the relative path in `/usr/lib64/cmake/gflags/gflags-config.cmake`, you could also 'fix' this for yourself alone by modifying the relative path in that file (or rebuilding the package yourself locally) which would at least have the benefit that it would fix the issue for any downstream clients, not just Ceres.  Most projects do not verify their dependencies to the same degree that Ceres does, and given that for system packages `/usr/include` is almost always on the path and so other projects might not notice as although the paths are wrong, the headers are still found when required.

If you can confirm that that issue is the relative path in `/usr/lib64/cmake/gflags/gflags-config.cmake` then you should report this issue to the Fedora maintainers.
