### ISSUE TITLE
Linking Ceres to GFlags unresolved symbol

### ISSUE THREAD

**Issue by jparcell** [ceres-solver/ceres-solver#519]
1>gflags_static.lib(gflags.obj) : error LNK2019: unresolved external symbol __imp_PathMatchSpecA referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl google::`anonymous namespace'::CommandLineFlagParser::ProcessOptionsFromStringLocked(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum google::FlagSettingMode)" (?ProcessOptionsFromStringLocked@CommandLineFlagParser@?A0x09ebb1d4@google@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV45@W4FlagSettingMode@3@@Z)
1

I've compiled glog, gflags and ceres and now I'm attempting to include ceres, referencing 
ceres.lib
gflags_static.lib
glog.lib

I'm down to just one linker error and I can't find where that symbol could be specified.

**Comment by jparcell** [comment]
Visual Studio 2017, Windows 10.

**Comment by alexsmac** [comment]
This looks like a gflags problem.  You appear to be missing the `shlwapi` Windows library (which defines PathMatchSpecA()) - that's odd as gflags should be bringing that dependency in [here](https://github.com/gflags/gflags/blob/28f50e0fed19872e0fd50dd23ce2ee8cd759338e/CMakeLists.txt#L481) if you are using a recent version of gflags that was built with CMake, and you are importing gflags as a CMake target in Ceres (rather than having Ceres try to find its library and header components separately (see docs for `GFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION` in Ceres).  If you *aren't* using an exported gflags configuration file then this could certainly happen as Ceres catches the typical link dependencies of gflags in this case, but won't necessarily catch all of them on Windows as it does not replicate all of the various Windows-specific checks in gflags' CMakeLists.

I'm going to close this, as this doesn't appear to be related to Ceres but rather the gflags target that you're using.
