### ISSUE TITLE
Eigen3 not found by cmake on Ubuntu

### ISSUE THREAD

**Issue by kgreenek** [ceres-solver/ceres-solver#541]
As of this commit (https://github.com/ceres-solver/ceres-solver/commit/33dd469a53383743af00a711a6a85e64c35177e8), Eigen fails to be found by cmake on Ubuntu 16.04.

When running cmake, the following error can be seen:
```
CMake Error at /home/kevin/src/ceres-solver/CMakeLists.txt:243 (find_package):
  Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.3".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown
```

Eigen is apt-installed. Reported version is:
```
libeigen3-dev/xenial,xenial,now 3.3~beta1-2 all [installed]
```

I tried removing the requirement for 3.3 and got other errors. I.E. changing line 243 in CMakeLists.txt from:
```
find_package(Eigen3 3.3 CONFIG REQUIRED
```
to
```
find_package(Eigen3 CONFIG REQUIRED
```

This gives me the following error:
```
  Target "ceres" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by kgreenek** [comment]
The version of eigen currently provided by apt for Ubuntu 16.04 is reported during cmake config as `3.2.92` (even though it's called 3.3 in apt).

**Comment by alexsmac** [comment]
Hi @kgreenek the issue is that vanilla 16.04's packages are pretty old now, and we're modernising our dependencies in preparation for Ceres 2.0 which will be coming early next year.  In addition to requiring Eigen >= 3.3 which allows us to remove some workarounds for issues with older Eigen versions (the 3.2.92 package in 16.04 is one of the pre-release betas (hence .92) rather than a true 3.3 release) we are trying to make the CMake configuration files generated Ceres truly relocatable.  This requires using the modern CMake-ified versions of our dependencies where possible.

With 20.04 around the corner, we didn't plan to support vanilla 16.04 in Ceres 2.0, only 18.04+.  If you wish to build/PPA newer versions of the dependencies yourself, then master will still build just fine on 16.04.  Alternatively, you can also use the current 1.14 release that will build with vanilla 16.04's dependencies.

What is your use-case for running Ceres' master branch on 16.04?

**Comment by kgreenek** [comment]
Thanks for the fast reply. That all sounds understandable.

We ran into this bug that was causing crashes for us: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/13640

Our solution for now is to create a private fork of 1.13 and cherrypick that fix.

We are building using catkin with ros kinetic fwiw.

**Comment by hanzheteng** [comment]
> When running cmake, the following error can be seen:
> 
> ```
> CMake Error at /home/kevin/src/ceres-solver/CMakeLists.txt:243 (find_package):
>   Could not find a configuration file for package "Eigen3" that is compatible
>   with requested version "3.3".
> 
>   The following configuration files were considered but not accepted:
> 
>     /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown
> ```
> 

I have encountered the same issue as the above one today. According to [this repo](https://github.com/gaoxiang12/slambook2/tree/master/3rdparty), the solution is to go back to an old version of ceres-solver. In other words, I just do `git reset --hard e51e9b46f6` and then (after installing dependencies) just cmake and make install.

Leaving a comment here just in case someone else finds this issue and needs a walkaround.
