### ISSUE TITLE
Codegen Optimizer Class Structure

### ISSUE THREAD

**Issue by darglein** [ceres-solver/ceres-solver#558]
I'm currently working on the codegen optimizer over here https://github.com/darglein/ceres-solver/tree/master/include/ceres/codegen/internal:

The current code structure is like this (simplified):
```
class Optimizer{
   std::vector<Optimization> 
}

class Optimization{
     virtual int apply(ExpressionGraph& graph) = 0;
}

class DeadCodeElimination : public Optimization{
    virtual int apply(ExpressionGraph& graph) override { ... }
}
```
Is this fine or do you prefer adding all `Optimizations` into `Optimizer` as member functions?

**Comment by sandwichmaker** [comment]
@darglein  there seems to be two very different questions here.

The first one is about class organization. The second seems to be about the level of abstraction. I do not understand how these two connect.  Can you say more?

**Comment by darglein** [comment]
Yeah the questions are not really related. Let's start with the class organization first :).

**Comment by sandwichmaker** [comment]
I am thinking about it from the perspective of testing and readability. I think it makes more sense for each optimization to be its own pass. which can be tested for its own invariants. Since there is no interaction between them, it is not clear to me why we would want to put them as members of the same class and then worry about what happens to the state of the class as each of them is called.
