### ISSUE TITLE
a 3rd party code may cause one of  my project couldnt use  ceres anymore

### ISSUE THREAD

**Issue by resplendent-star** [ceres-solver/ceres-solver#579]
-- Found required Ceres dependency: Eigen version 3.3.90 in /usr/local/include/eigen3
-- Failed to find glog - Could not find glog include directory, set GLOG_INCLUDE_DIR to directory containing glog/logging.h
CMake Error at /usr/local/lib/cmake/Ceres/CeresConfig.cmake:85 (message):
  Failed to find Ceres - Missing required Ceres dependency: glog.  Searched
  using GLOG_INCLUDE_DIR_HINTS:
  /home/lzw/resplendent_code/voxblox_pp_ws/devel/include and glog_DIR: .
Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:233 (ceres_report_not_found)
  CMakeLists.txt:14 (find_package)
--------------------------------------------------------------------------------------------------------------
by the way,I have already install  the  glog
when  I del the  voxblox_pp_ws,my project cant use ceres

**Comment by alexsmac** [comment]
As your glog install was in a non-standard location, Ceres was given its location when it was built.  In order to ensure that it can reference the public dependency when exported Ceres needs to record those paths, if you delete glog then yes, it will indeed not work as you have deleted a dependency of Ceres.  You should install glog, ideally to a standard system location and then rebuild Ceres using that version of glog.

**Comment by resplendent-star** [comment]
> As your glog install was in a non-standard location, Ceres was given its location when it was built. In order to ensure that it can reference the public dependency when exported Ceres needs to record those paths, if you delete glog then yes, it will indeed not work as you have deleted a dependency of Ceres. You should install glog, ideally to a standard system location and then rebuild Ceres using that version of glog.

thanks you very much,your are the god
