### ISSUE TITLE
Memory Increasing Unlimmited

### ISSUE THREAD

**Issue by YangSiri** [ceres-solver/ceres-solver#598]
Hi, great contributors. 

I'm facing the problem of **memory-run-out-of**. That's, I build and solve the non-linear optimization problem with 10 parameter blocks and around 3,000 residual blocks, several times repeated while the system goes on. But I saw the memory using is increasing and used up in the end(the computer became stucked and I had to turn the system off). So I wonder about how and when the memory of CERES is released. Could someone tell me how to solve this? 

The sample code is like below:
__(for iter 1 to 6){
    new lossfunc;
    new localpara;
    new problem;
    add parameterblocks;
    add residualblocks;  // every iter is different
    solve; 
}__

I also checked the system without running solver to filter out the other problem. It seemed fine, without big memory cosumption. 

Looking forward to your generous help ;)

**Comment by sandwichmaker** [comment]
can you create a small reproduction which shows the issue?

**Comment by YangSiri** [comment]
Sorry, @sandwichmaker, I dont get you.

I also used CERES in other problems. It worked just fine and the memory cosumption is stable. I just want to know what may cause CERES using large amount of memory of the system.

**Comment by sandwichmaker** [comment]
is the problem size increasing as part of the loop? what linear solver are you using? can you print some problem statistics out?

**Comment by YangSiri** [comment]
No, @sandwichmaker 

The problem size is similar in every iteration because it is reset every time.

The solve fullreport is as: 

> Solver Summary (v 2.0.0-eigen-(3.3.4)-lapack-suitesparse-(4.4.6)-eigensparse-openmp)

                                     Original                  Reduced
Parameter blocks                           10                        8
Parameters                                 35                       28
Effective parameters                       30                       24
Residual blocks                          5931                     5931
Residuals                                6897                     6897

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
Threads                                     8                        8
Linear solver ordering              AUTOMATIC                        8

Cost:
Initial                          8.684862e+00
Final                            7.242683e+00
Change                           1.442180e+00

Minimizer iterations                        8
Successful steps                            8
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                         0.006161

  Residual only evaluation           0.013706 (8)
  Jacobian & residual evaluation     0.164238 (8)
  Linear solver                      0.079533 (8)
Minimizer                            0.271037

Postprocessor                        0.000528
Total                                0.277727

Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 8.497317e-07 <= 1.000000e-06)

The main function is like:
_void solver(){
(for iter 1 to 6){
new lossfunc;
new localpara;
new problem;
add parameterblocks;
add residualblocks; // every iter is different
solve;
}}
int main(){
    solver();
}_

The main function runs at 10Hz.

**Comment by YangSiri** [comment]
![图片](https://user-images.githubusercontent.com/33154113/84215197-22c26d00-aaf8-11ea-8afd-a75786536049.png)
(The red is memory cosumption.)

**Comment by sandwichmaker** [comment]
its possible that your problem is getting denser, so the memory used by the sparse cholesky factorization is increasing. Thats the only possible reason I can think of. I would be quite surprised if there is a memory leak inside ceres.

**Comment by YangSiri** [comment]
okay, @sandwichmaker 

Thanks very much for your advice, bro. However, the problem, like i said, is not growing bigger or denser. I will check my programming for more times to see if there is any clue to this memory-using problem. And if you got new thoughts, please let me know~

**Comment by JzHuai0108** [comment]
I am struggling with the same situation for 2 months.
The problem is a bspline-based trajectory optimization. The traj is parameterized by a series of bspline control points which are to be optimized given camera reproj errors and inertial measurements.
We have a custom least squares optimizer which uses a [block cholesky solver](https://github.com/ethz-asl/aslam_optimizer/blob/master/aslam_backend/include/aslam/backend/BlockCholeskyLinearSystemSolver.hpp). It solves the problem very efficiently less than 1 minute with limited memory consumption 4.7% of the memory on a 32GB RAM laptop.
Now we build the problem in the ceres solver syntax and then solve it with the sparse normal cholesky. It keeps eating away the memory, and gets killed by the system when hitting the 80% of the memory usage.
To deal with this, our approach is to use the CGNR solver in ceres solver. Though it avoids memory explosion, it is much slower, taking more than 3 hours for the same problem.
The motivation to use the ceres solver is to inherit its auto diff. Now its solver is giving us the big headache.
My plan is to create an interface to the custom optimizer while using the autodiff in the implementation.
What do you think I can do to make ceres solver more memory efficient?

**Comment by sandwichmaker** [comment]
As far as we know there is no memory leak in ceres solver.  What sized
problem are you trying to solve? Have you tried to check your code for
memory leaks? Do you know what part of the code is allocating the memory
and not releasing?

**Comment by JzHuai0108** [comment]
I am also confident that ceres solver has no memory leaks. The size of the problem is given in the above post. The program with CGNR runs fine and gives good results, albeit real slow. So I am not suspecting memory leak in the code. If you think memory leak is a problem, I will try the address sanitizer which is already in place, but my previous experience with it was that it excavated lots of irrelevant memory problems about Eigen alignment. so I hardly use it with the present codebase. After the problem is built up, the memory use is still small like 2% of the total memory. The memory use climbs up when solve(problem) is invoked, with sparse normal cholesky option. In contrast, the memory use remains constant for CGNR.
The factors are pretty slim, and do not allocate memory during value and jacobian evaluation as far as I know.

**Comment by sandwichmaker** [comment]
I do not see the size of the problem in your post. Do you mean the link to
your  block solver?

If the memory usage is climbing during the solve then I suspect what is
happening is that the sparsity structure the way you have expressed it
while building the problem is causing the memory usage to explode - this
can happen with sparse cholesky.

What sparse linear algebra library are you using?

How many parameter blocks?

How many residual blocks?

How sparse is your Jacobian? Can you share the code you are using to
construct the problem?

**Comment by JzHuai0108** [comment]
Yes. This is also what I am suspecting.
```
options.sparse_linear_algebra_library_type = ceres::SUITE_SPARSE;
Number parameter blocks 6801
Number residual blocks 269222
```
We have several error terms, e.g., the reprojection error f(c1, c2, c3, c4, c5, t, l, p, R). The jacobian of f relative to these parameters, c1, c2, c3, c4, c5, t, l, p, R, are not zero.
I will invite you by email to see the codebase.

**Comment by sandwichmaker** [comment]
That is quite a large number of residuals.

You were able to solve this exact problem (same size) efficiently with your
block solver?

**Comment by JzHuai0108** [comment]
The problem is indeed large.
Our block solver can solve it efficiently, I feel it takes less than 1 minute.
Its log is given below, also in the early post.
```
Optimization problem initialized with 9016 design variables and 275847 error terms
The Jacobian matrix is 569642 x 40558
[0.0]: J: 2.61756e+07
[1]: J: 546994, dJ: 2.56286e+07, deltaX: 0.109586, LM - lambda:10 mu:2
[2]: J: 544323, dJ: 2671.75, deltaX: 0.124408, LM - lambda:3.33333 mu:2
[3]: J: 544322, dJ: 0.276194, deltaX: 0.0844534, LM - lambda:1.11111 mu:2
[4]: J: 544322, dJ: 0.000762564, deltaX: 0.00775962, LM - lambda:0.37037 mu:2
```

**Comment by sandwichmaker** [comment]
One thing which strikes me as odd is your use of DynamicAutoDiffCostFunction. Why are you using it? your functors are entirely compile time static in size.

**Comment by sandwichmaker** [comment]
Can you run your solver with -logtostderr -v=3 and share the output with me.

**Comment by JzHuai0108** [comment]
> One thing which strikes me as odd is your use of DynamicAutoDiffCostFunction. Why are you using it? your functors are entirely compile time static in size.

For splines parameterized by a few temporal adjacent control points,  we often want to estimate the time offset which necessitates more control points for a cost function. This was the motivation to use dynamic autodiff cost functions. But later we discard the time offset for simplicity and the dynamic autodiff becomes a relic. You are right that we should use autodiff cost functions in such cases.

**Comment by JzHuai0108** [comment]
> Can you run your solver with -logtostderr -v=3 and share the output with me.

Let's clarify it a bit. By "your solver", do you mean 
a. BlockCholesky in our custom optimizer
b. SparseCholesky in ceres solver
c. CGNR?

**Comment by JzHuai0108** [comment]
I tried 
```
rosrun bsplines_ceres bsplines_ceres_tests --gtest_filter="*KalibrStereoRadtan*" -logtostderr -v=3
```
It does not show anything more than the case without these extra arguments. Just "Killed" is shown.
I also managed to convert the ceres problem to a problem in the custom solver.
As a result, the two solvers, ceres and the custom solver are dealing with the same problem.
Surprisingly, the custom solver also consumes lots of memory, about 13% of the total memory.
And then the program gets disconnected from the "top" memory viewer in a terminal, though it seems to be alive in its own terminal.
I guess some factors use lots of memory in the evaluation step, and causing the memory blowup.
I have some suspect code snippets to look into.
I will check these places in the following days.
Do you have any advice about it?

**Comment by JzHuai0108** [comment]
I have checked these places and they all look innocent.
Later I found that the way I used the custom solver was wrong. With the corrections, it worked like magic again.
Briefly, the corrections include a. divide variables into two groups, calibration parameters, and other supporting parameters, b. use [an incremental problem builder](https://github.com/ethz-asl/aslam_incremental_calibration/blob/master/incremental_calibration/src/core/IncrementalOptimizationProblem.cpp). 
The latter is mysterious to me. It was meant to optimize the variables using selected observation batches, but I could not figure out how this was achieved in the code in two minutes.

After all, I think the memory explosion problem is probably due to the problem structure itself, and not due to some memory leak bugs.
I will stop working on it with a summary.
1. The ceres solver Sparse Normal Cholesky blows up the RAM. Sometimes, it manages to solve the problem in a short time like 10 minutes, the result also looks good to me.
2. The ceres solver CGNR keeps RAM use about 4%, and gets decent results, but takes at least 1 day.
3. The aslam optimizer2 also blows up the RAM. The program becomes a zombie, but not gets killed.
4. The aslam optimizer2 with the IncrementalCalibration problem keeps RAM use less than 6%, and gets excellent results in less than 3 hours.

**Comment by sandwichmaker** [comment]
sorry for the delay in replying. 

CGNR using a small amount of memory with crappy performance is not surprising. So lets not worry about it. 
I think as you have identified, the problem here seems to be the sparsity structure of the problem you are solving, which is causing the blow up. If you run the solver with -v=3, suitesparse dumps out its analysis information which looks something like this

```

CHOLMOD version 5.2.1, Mar 22, 2024: Symbolic Analysis: status: OK
  Architecture:
    sizeof(int):      4
    sizeof(int64_t):  8
    sizeof(void *):   8
    sizeof(double):   8
    sizeof(Int):      4 (CHOLMOD's basic integer)
    sizeof(SUITESPARSE_BLAS_INT): 4 (integer used in the BLAS)
  Results from most recent analysis:
    Cholesky flop count: 4.4505e+10
    Nonzeros in L:       1.6949e+07
  memory blocks in use:          11
  memory in use (MB):           0.6
  peak memory usage (MB):      47.4
  maxrank:    update/downdate rank:   8
  supernodal control: 1 40 (supernodal if flops/lnz >= 40)
  nmethods:   number of ordering methods to try: 1
    method 0: natural
        flop count: 4.4505e+10
        nnz(L):     1.6949e+07
  OK
I20240522 08:45:15.464191 1183638 wall_time.cc:77] 
```

this can give insight into whats going on with the cholesky factorization routines.

I have no idea what the incremental problem builder is and how it works.  I suspect it maybe doing some kind of coordinate descent. You can achieve the same with ceres by constructing your problem and then marking some variables as constant, running the solver and then flipping the constantness of the variables.

Another suggestion is that you could try a different ordering scheme. The default is AMD but if you have metis available, you can use NESDIS/nested dissection which can sometimes lead to very significant savings in memory and time depending on the sparsity of the problem and maybe your problem is amenable to that.

**Comment by JzHuai0108** [comment]
No worries.

I will try to figure out why -v3 is not showing anything in the stdout and share the output.

**Comment by JzHuai0108** [comment]
I cannot figure out why -v=3 is not printing anything.
I tried these setups:
```
./devel/lib/bsplines_ceres/reproj_test -logtostderr -v=3 # in main
./devel/lib/bsplines_ceres/reproj_test --logtostderr --v=3 # in main
rosrun bsplines_ceres bsplines_ceres_tests --gtest_filter="*KalibrStereoRadtan*" -logtostderr -v=3 # in gtest
rosrun bsplines_ceres bsplines_ceres_tests --gtest_filter="*KalibrStereoRadtan*" --logtostderr --v=3
```
All setups prints the same as shown below
```
# for problem 1
Optimizing problem...
Number parameter blocks 6801
Number residual blocks 269222

Solver Summary (v 2.1.0-eigen-(3.3.7)-lapack-suitesparse-(5.7.1)-cxsparse-(3.2.0)-eigensparse-no_openmp-cuda-(11050))

                                     Original                  Reduced
Parameter blocks                         6801                     6657
Parameters                              23738                    23306
Effective parameters                    20409                    19977
Residual blocks                        269222                   269222
Residuals                              556388                   556388

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
Threads                                     7                        7
Linear solver ordering              AUTOMATIC                     6657

Cost:
Initial                          7.126537e+07
Final                            1.586364e+05
Change                           7.110674e+07

Minimizer iterations                       19
Successful steps                           19
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                         5.920875

  Residual only evaluation           3.069640 (19)
  Jacobian & residual evaluation    12.271993 (19)
  Linear solver                    651.387063 (19)
Minimizer                          680.062654

Postprocessor                        0.043583
Total                              686.027112

Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 7.276611e-07 <= 1.000000e-06)

# for problem 2
Optimizing problem...
Number parameter blocks 9127
Number residual blocks 269222
Killed

```
