### ISSUE TITLE
DynamicAutoDiffCostFunction and SetParameterLowerBound

### ISSUE THREAD

**Issue by HumamHelfawi** [ceres-solver/ceres-solver#638]
Is it possible to use `DynamicAutoDiffCostFunction  `& `SetParameterLowerBound `in the same time. I am getting error saying index out of range when I am trying to use `SetParameterLowerBound `.

Example:
```
for (size_t pnt_idx = 0; pnt_idx < points_a.size(); pnt_idx++)
{
	auto cost_function_obj = new HCostFunctor(points_a[pnt_idx], points_b[pnt_idx]);
	auto* cost_function = new ceres::DynamicAutoDiffCostFunction<HCostFunctor>(cost_function_obj);
	cost_function->SetNumResiduals(2);
	cost_function->AddParameterBlock(1);
	cost_function->AddParameterBlock(1);
	cost_function->AddParameterBlock(2);
	std::vector<double*> params{ &parameters[0 + i * 3], &parameters[3 + i * 3], &parameters[1 + i * 3] };
	problem.AddResidualBlock(cost_function, NULL, params);
}
problem.SetParameterLowerBound(parameters, 0 + static_cast<int>(i) * 3, 1);
problem.SetParameterUpperBound(parameters, 0 + static_cast<int>(i) * 3, 200000);
```

**Comment by sandwichmaker** [comment]
1. why are you using dynamicautodiffcostfunction? your functor takes 2
parameter blocks and has a fixed number of residuals.
2. Also you are using SetParameterLowerBound incorrectly. the index is
supposed to be within a particular parameter block, since your parameter
blocks are of size 1 or 2 how can your index be i * 3?

**Comment by HumamHelfawi** [comment]
Thanks, this is a small part of the example, I had to use dynamicautodiffcostfunction since there is another part which add more residuals that uses the same parameters in different order which triggered an exception regarding "Aliasing". I read somewhere that the solution is to sperate the blocks and use dynamicautodiffcostfunction which worked for me.

>  Also you are using SetParameterLowerBound incorrectly. the index is
> supposed to be within a particular parameter block, since your parameter
> blocks are of size 1 or 2 how can your index be i * 3?

This exactly my questions...
May you please elaborate a bit how should I mention the first parameter in the first block or the second parameter in the third block correctly?

**Comment by sandwichmaker** [comment]
actually there is a bigger problem.
you have three parameter blocks but they sum up to size 4 and your loop
assumes that they are three apart since you are doing i * 3 no? Thats
likely why you are getting aliasing exceptions.

either ways the way the call works is

SetParameterLowerBound(parameter_bloock, index_inside_parameter_block,
bound)

here parmeter_block is the pointer to the parameter block so in your case
you will have calls of the sort

SetParameterLowerBoubd(&parameters[index_of_first_parameter_block], 0,
lower_bound);
SetParameterUpperBound(&parameters[index_of_third_parameter_block], 1,
upper_bound);

**Comment by HumamHelfawi** [comment]
Thanks for taking the time to examine the problem. Actually, my parameters are as follow:
F0, P0, T0, F1, P1, T1, F2 P2 ....

Each Residual needs 4 parameters [Fi] [Pi] [Ti] and [Fi+1],  because of that I am using 3*i since the last one is shared between two residuals. Is there a better way to do it?

**Comment by HumamHelfawi** [comment]
BTW, Upper and lower bound worked exactly as you mentioned . Thank you very much!
