### ISSUE TITLE
Issue reading arguments in pose_graph_2d

### ISSUE THREAD

**Issue by b4sgren** [ceres-solver/ceres-solver#656]
When I run the pose_graph_2d example the executable always fails at the check on line 164 (CHECK(FLAGS_input != "")). I have checked the arguments passed to the program via argv and the filename is there but it is failed to be correctly parsed. I got the executable working by replacing FLAGS_input with argv[1] on lines 164 and 169 (where the file is being read). I wasn't sure where to go to fix the parsing issue.

I'm on Ubuntu 20.04 with cmake version 3.16.3 and gcc version 9.3.0.

**Comment by alexsmac** [comment]
The issue is that you are not specifying the input file correctly.  Each gflag value must be proceeded by the name of the flag, so in this case you should invoke the application as follows: `pose_graph_2d -input <FILENAME>`, any extra unqualified values passed will be ignored by the gflags library during parsing.  You can see a full list of the available gflags via `-help`.
