### ISSUE TITLE
Non deterministic behavior in schur elimination

### ISSUE THREAD

**Issue by ghost** [ceres-solver/ceres-solver#664]
Hello,

I observed a non deterministic behavior when using ceres solver for a bundle adjustment problem.

- Launch the same program with exactly the same data twice : the result provided by ceres changes.
- If we disable threading in ceres, it is deterministic.

Going deeper and deeper in the code, I found that the problem lies in the function

`SchurEliminator<kRowBlockSize, kEBlockSize, kFBlockSize>::Eliminate`

https://github.com/ceres-solver/ceres-solver/blob/2b32b321242b32f6364108694e0069f87e56326c/internal/ceres/schur_eliminator_impl.h#L177

If, in this function, i replace `num_threads_` with the constant value 1, then the algorithm become deterministic.

I would bet on a problem of floating point approximation between large and small values (depending on the processing order)

I can't share the data where the problem appears.

Thanks,

Fabien

**Comment by sandwichmaker** [comment]
This is a known issue. Threading, floating point operations on poorly conditioned operations are a problem.

**Comment by fabiencastan** [comment]
@sandwichmaker Could we accumulate per thread and merge the results at the end to ensure the repeatability? This would ensure that the processing order between the threads will not change the final result.

**Comment by sandwichmaker** [comment]
That will not fix the problem Fabien. Since the distribution of work per thread is not deterministic either. But suppose it does do that, we will still need to spend num_threads copies of the schur complement to do this, which is not at all cheap for problems where threading matters.

The fact that you are seeing different results indicates that the problem is quite numerically sensitive/poorly conditioned. It is better to think about scaling the problem so that it is less poorly conditioned.

**Comment by fabiencastan** [comment]
Thank you for the explanation.
