### ISSUE TITLE
compile error: 2 * Jet<double, 1>();

### ISSUE THREAD

**Issue by federkamm** [ceres-solver/ceres-solver#695]
Multiplying a `Jet<double, 1>` by an integral constant results in a compiler error.  That is quite unfortunate as libraries sometimes use code like

```c++
template <typename T>
T important_function(T x) {
  return 2 * x;
}
```

and Ceres can't auto differentiate them.

Minimal example:

```c++
#include <ceres/ceres.h>
int main() {
  2 * ceres::Jet<double, 1>();
  return 0;
}
```

**Comment by federkamm** [comment]
See Pull Request #696 for a possible solution

**Comment by sandwichmaker** [comment]
This is by design. We disallow binary operations with integers because it is the source of a lot of inadvertent errors in the past.

**Comment by federkamm** [comment]
Can you explain a little bit on this or give a reference to such an error?  From a mathematical point of view I would expect the natural morphism IZ -> R from the integers to a Ring/Algebra exists (ie. is implemented) and doesn't cause troubles.

**Comment by sandwichmaker** [comment]
There is no mathematical problem. The problem is that if you allow integer arguments, then it is very easy for people to make errors of the form -- lookup_array[std::floor(x)], i.e. use the integer part of an input argument and use it as an index into a lookup array an expect that the derivatives are computed correctly. Or even worse just compute the integer part of x and use it in some computation, without realizing what truncating like that does to the derivative computation process.

Yes if the user is careful enough then they can avoid errors like this, but experience has taught me that this flexibility is not worth it.
