### ISSUE TITLE
Question on exact (down to patch level) Eigen version requirement

### ISSUE THREAD

**Issue by traversaro** [ceres-solver/ceres-solver#704]
Hi Ceres mantainers! First of all, thanks a lot for the amazing work on Ceres. 

I am opening this issue as while packaging ceres in [conda-forge](https://conda-forge.org/), we had a doubt on the reason why, when consuming the compiled version of Ceres, it is required to have the exact version of Eigen used to compiled Eigen? 

In our limited experience, Eigen 3.* is rather ABI stable, so while we understand why there could be a requirement that Eigen version used downstream is >= of the version used to compile Ceres, the strict requirements of having exactly the same version of Eigen down to the patch version seems to indicate that Eigen3 breaks its API even in patch versions. So we were wondering if you had more details on this requirements, thanks in advance.

See https://github.com/conda-forge/ceres-solver-feedstock/issues/19 and https://github.com/conda-forge/ceres-solver-feedstock/pull/23#issuecomment-923220679 for some related discussions.

**Comment by sandwichmaker** [comment]
Eigen is header only, and Ceres has templated parts which depend on Eigen. Therefore instead of trying to guess where the ABI breaks across versions of Eigen we demand that you use the exact same version of Eigen.

**Comment by alexsmac** [comment]
To add more context to this, Eigen ABI incompatibilities have been
identified as the source of a number of reported issues both on the mailing
list and internally over the years.  As it is header only, and exposes
macros which can significantly modify the compiled result (as well as being
sensitive to the compilation flags used), our experience has been that ODR
violations can occur frequently in practice.  Eigen should not be *assumed*
to be ABI-compatible between versions, and there have been various tickets
raised about this for Eigen (e.g. here
<https://gitlab.com/libeigen/eigen/-/issues/1349>).

Identifying the root cause of several of these issues was time consuming
and tedious.  Forcing identical versions of Eigen when compiling and using
Ceres is a mitigation step we decided to take to reduce the likelihood of
more of these kinds of bugs cropping up in downstream clients.

**Comment by sandwichmaker** [comment]
I will assume that this issue has been resolved, please feel free to re-open it if you have further questions.
