### ISSUE TITLE
Compiling fails on Debian unstable

### ISSUE THREAD

**Issue by bgermann** [ceres-solver/ceres-solver#715]
Debian unstable switched to a newer set of buildtools (GCC, autoconf updated). ceres-solver 2.0.0 fails to build with those changes. You can find a build log at https://salsa.debian.org/science-team/ceres-solver/-/jobs/2134101/raw

**Comment by alexsmac** [comment]
This doesn't look like a problem with Ceres, but with its dependencies - specifically gflags and glog.  The latter depends on the former, and the installed CMake target config for glog (`/usr/lib/x86_64-linux-gnu/cmake/glog`) is returning `glog::glog` as the imported target on which Ceres should depend, which is then being resolved to the *static* library, which is in turn presumably statically linked to gflags.

However, the CMake target config for gflags (`/usr/lib/x86_64-linux-gnu/cmake/gflags`) is returning the *shared* target when invoked by Ceres.  That means that, indirectly, you are linking both the static and shared versions of gflags which is why the resulting Ceres executables are failing.

This looks like a bug in at least one of the exported CMake configurations, as CMake should ensure that a consistent (by default the shared versions) of dependencies are used.  It could be that your installed glog config is forcing the use of the static one for some reason (both are listed in the package [here](https://packages.debian.org/sid/amd64/libgoogle-glog-dev/filelist))

**Comment by sergiud** [comment]
> [...] as CMake should ensure that a consistent (by default the shared versions) of dependencies are used.

CMake documentation for the `find_package` command does not seem to mention such a rule. Can you point me to CMake documentation where this behavior is specified?

To my knowledge, CMake does not care about library type the package targets contain. It is the responsibility of the consumer (i.e., user) to ensure targets and thus library types are compatible among each other. Therefore, the problem is caused by Debian which employs a mix of library types not supported by glog and gflag combination.

**Comment by alexsmac** [comment]
> CMake documentation for the `find_package` command does not seem to mention such a rule. Can you point me to CMake documentation where this behavior is specified?

It's alluded to in the documentation for `find_library()` [here](https://cmake.org/cmake/help/v3.19/command/find_library.html):

> Each library name given to the NAMES option is first considered as a library file name and then considered with platform-specific prefixes (e.g. lib) and suffixes (e.g. .so). Therefore one may specify library file names such as libfoo.a directly. *This can be used to locate static libraries on UNIX-like systems.*

There have been various [issues](https://cmake.org/Bug/view.php?id=1643) and [messages](https://cmake.org/pipermail/cmake/2010-December/041326.html) on the CMake mailing list about it over the years, they are old but AFAIK the behaviour is unchanged, and I think the cause (a Windows issue) is still unchanged.

However, I think ^ is a red-herring here.  I downloaded the .deb packages and inspected the contents and the installed `glog::glog` definition appears to be very explicitly static *only*:

```cmake
# Import target "glog::glog" for configuration "Release"
set_property(TARGET glog::glog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(glog::glog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/x86_64-linux-gnu/libglog.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS glog::glog )
list(APPEND _IMPORT_CHECK_FILES_FOR_glog::glog "${_IMPORT_PREFIX}/lib/x86_64-linux-gnu/libglog.a" )
```

There appears to be no reference whatsoever to the also installed `libglog.so`.  By contrast, the `gflags-config.cmake` is defaulting to using `gflags_shared` unless an alternative is specified (which it is not by Ceres).

This looks like an issue with the Debian package for glog to me.  It looks like it was built dynamically, then installed, then rebuilt statically and reinstalled so the shared library itself was copied, but the associated CMake config files were overwritten.  Certainly from a quick look at the current glog CMakeLists, it (like almost every project) is expecting to be built as one or the other, but not both.

**Comment by bgermann** [comment]
Thanks for the comments. This is indeed a glog issue in Debian.

**Comment by sergiud** [comment]
> It's alluded to in the documentation for `find_library()` here

No, is not. How is that reference even relevant? Package targets generally do not use `find_library` to begin with.
