### ISSUE TITLE
Issue with finding Eigen3

### ISSUE THREAD

**Issue by romanis** [ceres-solver/ceres-solver#717]
Hi, I am using some advanced eigen functionality like seq and last that is not yet part of ubuntu libeigen3-dev package, so, I installed eigen 3.4 from source and I installed it with cmake, putting it in standard location: 
~~~
romanistomin@pop-os:~/pcm_inversion/build$ sudo find / -type f -iname eigen3config.cmake
/home/romanistomin/Documents/eigen/build/Eigen3Config.cmake
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
/usr/share/eigen3/cmake/Eigen3Config.cmake
~~~
I then set in my own cmake project the location of eigen so that it can be found: 
~~~
set(Eigen3_DIR "/usr/share/eigen3/cmake/")
~~~
and my project can find eigen without problem, I use linear algebra normally. 

Then I need to do some nonlinear optimization and I install ceres according to manual except for the libeigen3-dev library since I already have eigen installed. 

And I get this when trying to find package Ceres in cmake: 

~~~
CMake Error at /usr/local/lib/cmake/Ceres/CeresConfig.cmake:89 (message):
  Failed to find Ceres - Missing required Ceres dependency: Eigen version
  3.4, please set Eigen3_DIR.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:210 (ceres_report_not_found)
  CMakeLists.txt:18 (find_package)


CMake Warning at CMakeLists.txt:18 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/Ceres/CeresConfig.cmake

  but it set Ceres_FOUND to FALSE so package "Ceres" is considered to be NOT
  FOUND.
~~~

I go to the Ceres cmake and replace `if (EIGEN3_FOUND)` to `if (Eigen3_FOUND)` in line 196 of CeresConfig.cmake and it works fine.

Is this a typo in your cmake or does manual installation of eigen produce different macros from the `apt get` installation?

**Comment by alexsmac** [comment]
This shouldn't be necessary no, in the 3.4 release of Eigen, Eigen3Config.cmake sets `EIGEN3_FOUND` [here](https://gitlab.com/libeigen/eigen/-/blob/3147391d946bb4b6c68edd901f2add6ac1f31f8c/cmake/Eigen3Config.cmake.in#L12), what is the contents of your `Eigen3Config.cmake` ?

**Comment by sergiud** [comment]
@alexsmac Note that those are legacy variables which [were removed](https://gitlab.com/libeigen/eigen/-/commit/f2984cd0778dd0a1d7e74216d826eaff2bc6bfab#618d329ccc83294fb4adc1383903316e95a1236d) and thus will not be available in future releases of Eigen (likely starting with 3.5). The correct variable to be checked against for detecting the presence of the package config is `Eigen3_FOUND` anyway.

**Comment by alexsmac** [comment]
Yes, @sergiud they were left over from when Ceres was updated to (only) use Eigen's own Config.  They have been updated in [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/19260)

**Comment by alexsmac** [comment]
@romanis if you're able to use the latest master branch of Ceres, this problem should be fixed

**Comment by Medoalmasry** [comment]
I know that this issue is closed, However, if someone is finding it difficult to build ceres-solver using linux-distro native Eigen libraries. Here is a break down of how to fix it:-

Version Details
Opensuse 15.3
Eigen 3.3.4
Ceres-solver (master date 22nd Jan)

In **opensuse** the default path for eigen is /usr/include/eigen3/Eigen which is apparently not the conventional place for it.
1) Go to /usr/share/cmake/Modules/FindEigen3.cmake
2) Add `set(EIGEN3_INCLUDE_DIR "/usr/include/eigen3")` right before the first if condition

If you try to build **ceres-solver** you will get an error while generating files (Eigen3::Eigen)
1) Go to ceres-solver/internal/ceres/CMakeLists.txt
2) Search for `target_link_libraries(ceres PUBLIC Eigen3::Eigen)` and comment it (by adding # before the line)

Now your build should be successful. However, if you try building something that uses ceres as a dependency (for instance colmap) you will find an error saying that ceres can't find eigen3
1) Go to /usr/local/lib64/cmake/Ceres/CeresConfig.cmake
2) Change `if (Eigen3_FOUND)` to `if (EIGEN3_FOUND)`
3) Repeat for else and endif

**Comment by sergiud** [comment]
Eigen 3.3.4 was released [almost 5 years ago](http://eigen.tuxfamily.org/index.php?title=News:Eigen_3.3.4_released!). You should consider updating. The workaround you described is not necessary and looks like a problem of the distro package even with this version of Eigen.

**Comment by Medoalmasry** [comment]
You're absolutely right, I deleted my comment to avoid someone else falling in the same problem.
