### ISSUE TITLE
Windows : error C2589 C2062 C2059 C2589

### ISSUE THREAD

**Issue by YohannPerron** [ceres-solver/ceres-solver#718]
Hi,
I have been struggling the whole day getting Ceres to compile on Windows. I just manage to get it working and wanted to give some additional info not on the documentation.
After following the documentation I have been faced with a wall of error such as: 

>  C:\lib\ceres-solver\internal\ceres/schur_eliminator_impl.h(151,27): error C2589: '(' : jeton non conforme à droite de '::' [C:\lib\ceres-solver\ceres-bin\internal\ceres\ceres.vcxproj]
>   C:\lib\ceres-solver\internal\ceres/schur_eliminator_impl.h(151,1): error C2062: type 'unknown-type' inattendu [C:\lib\ceres-solver\ceres-bin\internal\ceres\ceres.vcxproj]
>   C:\lib\ceres-solver\internal\ceres/schur_eliminator_impl.h(151,1): error C2059: erreur de syntaxe : ')' [C:\lib\ceres-solver\ceres-bin\internal\ceres\ceres.vcxproj]
>   C:\lib\ceres-solver\internal\ceres/schur_eliminator_impl.h(151,27): error C2589: '(' : jeton non conforme à droite de '::' [C:\lib\ceres-solver\ceres-bin\internal\ceres\ceres.vcxproj]

It seems to be related to the macro max define in define in widows.h. Following the advice on [https://www.developpez.net/forums/d428891/c-cpp/cpp/erreur-compilation-etrange/](url) (sorry it is in french), I have manage to get it working by adding a define NOMINMAX (or more precisely adding `add_compile_definitions(NOMINMAX)` to cmakes files).

I hope it helps someone.

Using cmake 3.19.4 and MSBuild 16.8.3.61104

**Comment by sandwichmaker** [comment]
Could this and https://github.com/ceres-solver/ceres-solver/issues/716 be the same underlying issue?

**Comment by XJTUbopenghui** [comment]
I added "#define NOMINMAX" in the config.h headfile, and added #undef min and #undef max in the jet.h.
All the errors disappear.

**Comment by sergiud** [comment]
> Could this and #716 be the same underlying issue?

Yes, it is the same issue.

`NOMINMAX` is a possible workaround that, however, can be applied to the Ceres code base only: since Jet is used in user code too, `NOMINMAX` would need to be propagated to dependencies as well which can break these if they rely on the `min`/`max` macro definitions.

A `NOMINMAX` agnostic approach would therefore be to prevent macro substitution in `std::max`, `std::min`, and also `std::numeric_limits<>::max()` and `std::numeric_limits<>::min()` calls.

**Comment by sandwichmaker** [comment]
Can we add a msvc version based warning to the jet header?

**Comment by sergiud** [comment]
I actually have a workaround which I will submit for review.

**Comment by sandwichmaker** [comment]
Awesome!

**Comment by emorell96** [comment]
I wanted to add for the record if anyone else finds this issue when struggling with this error. You can either add the #define NOMINMAX or in here: https://github.com/ceres-solver/ceres-solver/blob/f68321e7de8929fbcdb95dd42877531e64f72f66/include/ceres/local_parameterization.h#L343 put some parenthesis around the std::max call as such:
![image](https://user-images.githubusercontent.com/20151415/197441327-7237e6a5-1bb5-49d7-976d-c4802072c3d7.png)

This should no longer be an issue with v2.2 since they are removing this whole file, but in v2.1 that issue is still present in that file which causes a compilation error on Windows with MSVC.

**Comment by sandwichmaker** [comment]
This has been fixed at head I believe.

**Comment by emorell96** [comment]
I was building from what VSPKG installed and it installed the 2.1 version and that file (local_parameterization.h) lacked the parenthesis around the `std::max` causing the issue on Windows. 

As I said in the comment above this is no longer an issue for the future versions since that file doesn't even exist in the master branch :) but some people might find this issue when facing the issue with the current version like I just did 10 minutes ago.

**Comment by sandwichmaker** [comment]
Ah sorry I should have read more carefully.
