### ISSUE TITLE
Integrate sergiu's cmake suitesparse distribution into the ceres build

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#728]
https://github.com/sergiud/SuiteSparse is a maintained fork of SuiteSparse, this will be especially helpful on windows. 

@sergiud can you work with @alexsmac on this?

**Comment by sergiud** [comment]
This is great! I'd be glad to help.

The changes necessary involve the use of CMake import targets in `FindSuiteSparse.cmake` and their actual use here
https://github.com/ceres-solver/ceres-solver/blob/1f374a9fe53e362ab76fb36e1dc53f6609991009/internal/ceres/CMakeLists.txt#L212
replacing `CXSPARSE_LIBRARIES` by `CXSparse::CXSparse` and here
https://github.com/ceres-solver/ceres-solver/blob/1f374a9fe53e362ab76fb36e1dc53f6609991009/internal/ceres/CMakeLists.txt#L206
replacing `SUITESPARSE_LIBRARIES` by `SuiteSparse::CHOLMOD` and `SuiteSparse::SPQR`.

Similar changes have been [proposed before](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/16240) by @NeroBurner. But it seems no progress has been made since.

**Comment by sandwichmaker** [comment]
gentle ping?

**Comment by sergiud** [comment]
@alexsmac Would you like me to take over?

**Comment by sandwichmaker** [comment]
I suspect @alexsmac would be more than happy to review a CL from you.

**Comment by NeroBurner** [comment]
I've got a branch based on v2.0.0 which depends on https://github.com/jlblancoc/suitesparse-metis-for-windows generated targets, used to get `ceres-solver` using the [Hunter Dependency Manager](https://github.com/cpp-pm/hunter). Maybe the changes of that branch are of assistance 

https://github.com/cpp-pm/ceres-solver/tree/hunter-2.0.0
