### ISSUE TITLE
SizedCostFunction with CostFunctionToFunctor evaluates also constant Jacobian

### ISSUE THREAD

**Issue by moberweger** [ceres-solver/ceres-solver#768]
I slightly extended the [analytic example](https://github.com/ceres-solver/ceres-solver/blob/master/examples/helloworld_analytic_diff.cc) to work with two independent variables and a `CostFunctionToFunctor` wrapper. I noticed a strange behavior when setting one of the variables constant. When using the `SizedCostFunction` directly, the Jacobian of the constant variable is not computed (ie the parameter is set to `nullptr` and thus skipped). On the other hand, if I use a `CostFunctionToFunctor` wrapper and do the same optimization, both Jacobians are computed, also the irrelevant constant one. The optimization result is the same, but this irrelevant evaluation can lead to computational overhead in more realistic scenarios. One could now hack in a boolean variable to skip the computation. However, what I am asking myself if this behavior is expected, and is there a clean way to circumvent this limitation? Feedback is highly appreciated!

MWE to reproduce the issue can be found below. Tested with ceres 1.14. Use the `SWITCH THIS` comment below to switch between the different modes.

```
#include <vector>
#include "ceres/ceres.h"
#include "glog/logging.h"
using ceres::AutoDiffCostFunction;
using ceres::CostFunction;
using ceres::CostFunctionToFunctor;
using ceres::Problem;
using ceres::SizedCostFunction;
using ceres::Solve;
using ceres::Solver;

class OurCostFunction : public SizedCostFunction<1, 1, 1>
{
public:
  OurCostFunction() {}
  virtual bool Evaluate(double const *const *parameters,
                        double *residuals,
                        double **jacobians) const
  {
    double x = parameters[0][0];
    double y = parameters[1][0];
    // f(x) = 10 - x + y
    std::cout << "Compute residual" << std::endl;
    residuals[0] = 10 - x + y;

    if (jacobians == nullptr)
    {
      return true;
    }
    if (jacobians[0] != nullptr)
    {
      std::cout << "Compute jacobian 0" << std::endl;
      jacobians[0][0] = -1;
    }
    if (jacobians[1] != nullptr)
    {
      std::cout << "Compute jacobian 1" << std::endl;
      jacobians[1][0] = 1;
    }
    return true;
  }
};

struct Residual
{
public:
  Residual() : eval_ptr(new OurCostFunction()),
               error_eval_function(eval_ptr) {}

  template <typename T>
  bool operator()(const T *const x,
                  const T *const y,
                  T *residuals) const
  {
    // other stuff happens here...
    return error_eval_function(x, y, residuals);
  }

  OurCostFunction *eval_ptr;
  CostFunctionToFunctor<1, 1, 1> error_eval_function;
};

int main(int argc, char **argv)
{
  google::InitGoogleLogging(argv[0]);
  double x = 0.5, y = 0.2;
  const double initial_x = x, initial_y = y;
  Problem problem;
#if 1  // SWITCH THIS
  CostFunction *cost_function = new AutoDiffCostFunction<Residual, 1, 1, 1>(new Residual);
#else
  CostFunction *cost_function = new OurCostFunction;
#endif
  problem.AddResidualBlock(cost_function, nullptr, &x, &y);
  problem.SetParameterBlockConstant(&y);
  // Run the solver!
  Solver::Options options;
  options.minimizer_progress_to_stdout = true;
  Solver::Summary summary;
  Solve(options, &problem, &summary);
  std::cout << summary.BriefReport() << "\n";
  std::cout << "x : " << initial_x << " -> " << x << "\n";
  std::cout << "y : " << initial_y << " -> " << y << "\n";
  return 0;
}

```

**Comment by sandwichmaker** [comment]
@moberweger what you are observing has nothing to do with CostFunctionToFunctor but rather how AutoDiffCostFunction is implemented. AutoDiffCostFunction will evaluate the functor on all its input variables (constant or otherwise) and then when filling out the jacobians will only fill out the ones which are non-constant.

You can see the implementation of this at 

https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/internal/autodiff.h#L286

Of course this begs the question as to why do this?

The reason is that AutoDiffCostFunction uses template specialization to evaluate derivatives and the size of the underlying Jet object is compile time specified to be the sum of the sizes of all the parameter blocks that are input to the costfunction. This is a significant factor in the efficiency of autodiff, as it exposes all derivative computations as fixed sized array operations to the compiler.

However setting parameter block constant/variable is a runtime capability and  varying the template size at runtime will either make the code very slow OR if we generate code for all the 2^k - 1 possible combinations of parameter blocks being constant or variable, it will lead to code bloat.

**Comment by moberweger** [comment]
Thanks @sandwichmaker for this profound and quick answer. It makes things more clear now!
