### ISSUE TITLE
Make ceres more compatible with cmake's `fetch_content()`

### ISSUE THREAD

**Issue by cpp977** [ceres-solver/ceres-solver#773]
All cmake variables within ceres are not prefixed by `CERES_` which would serve as a namespace for cmake variables.
This is especially useful, if one uses ceres via cmake's `fetch_content()` because all the cmake variables of ceres are the imported to other projects.
I can imagine that this would be quite a breaking change but is there any chance that this will be changed in the future?

**Comment by sergiud** [comment]
The open question is: why would you want to prefix every single Ceres variable? Doesn't `FetchContent` already work as is?

My guess is that you assume the options of every single project integrated using `FetchContent` should be independent from each other. This however has a number of implications, also for CMake native options such as `BUILD_SHARED_LIBS`, `BUILD_TESTING`, etc. which would require special treatment as well just for this specific use case. However, there's also the other side where users do not want options to be independent which needs to be considered as well and will cause considerable code churn.

In my experience, providing maximum flexibility for supporting `FetchContent` is not worth the implementation/maintenance effort particularly because `FetchContent` limitations can be overcome using CMake's `ExternalProject`.

**Comment by alexsmac** [comment]
We did have a request in the distant past to investigate something like this for `FetchContent()` but the magnitude of the changes, and the detrimental effect on legibility within Ceres did not justify it.  AFAIK, few major projects have tried to support this use-case, and as @sergiud  says `ExternalProject()` would allow you to achieve a similar effect without requiring these changes.  Another option would be to use something like [Conan](https://docs.conan.io/en/latest/) which works well with CMake, it may be a large hammer for what you are trying to achieve though and not a viable option for you if this is part of an individual project.

I'm going to close this ticket, because for now I think our decision stands that we would consider making this change

**Comment by cpp977** [comment]
Sure no problem, another option is [vcpkg](https://vcpkg.io/en/index.html) which also integrates well with cmake.
