### ISSUE TITLE
Use ABSL

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#780]
googletest is going to take ABSL as a dependency. 

Once ABSL gains the ability to do logging, we should replace our use of glog, miniglog and gflags with ABSL. This will also allow us to remove a bunch of our internal forks like FixedArray too.

**Comment by sandwichmaker** [comment]
Now that the logging library is part of abseil 

https://github.com/abseil/abseil-cpp/tree/master/absl/log

we should be able to replace our use of gflags and glog with absl.

**Comment by S-o-T** [comment]
Any progress on this one? I did a quick test changing std::set to absl::btree_set for block_pairs in SparseSchurComplementSolver::InitStorage and BlockRandomAccessSparseMatrix ctor to achieve significant speedup for InitStorage. I guess there might be other similar low-hanging optimizations to be enabled by usage of abseil containers.

**Comment by sandwichmaker** [comment]
Hi Mark,

I was waiting for vlog support to land in absl, which seems to have happened recently. 

I suspect there are significant savings all over. Some of the datastructures absl offers are quite nice in that regard. 
Would you like to take a whack at this? the first thing to try would be to see if we can cleanly just replace the use of glog with absl/log  and remove the use of glog as well as miniglog. Once that is working well, we can look into using absl more extensively. 

If there are still problems with using absl for logging, then I would like to know so I can go bug the absl maintainers.

**Comment by S-o-T** [comment]
I will try to find some time for that, not sure about the priority though.

**Comment by sandwichmaker** [comment]
If you do not get a chance, then I will try and find some time in the next
week or so.

**Comment by AustinSchuhBRT** [comment]
I'm trying to upgrade one of our repositories which depends on ceres.  Mixing gflags + glog + absl flags and logging doesn't appear to go super well, so I took a stab.  I got the Bazel build to pass, but I am very much not a cmake expert, so any help there is appreciated.

**Comment by AustinSchuh** [comment]
I'm trying to upgrade one of our repositories which depends on ceres. Mixing gflags + glog + absl flags and logging doesn't appear to go super well, so I took a stab. I got the Bazel build to pass, but I am very much not a cmake expert, so any help there is appreciated.

**Comment by sandwichmaker** [comment]
Thanks Austin, I also have a draft change for this.

The change to using logging and flags while tedious seems fairly
straightforward.

The bigger problem is whether we should depend on the system installed absl
or the one at head.

The former for the current Ubuntu lts release is way out of date and does
not support logging properly (especially vlog), but if we decide to ship a
copy of absl with our own core or as a git submodule, then we risk creating
ODR violations with libraries compiled against the version of absl that's
installed on the system.

I am not sure what the right path forward here is.

**Comment by sandwichmaker** [comment]
Here is the draft CL I was working with a few weeks ago 

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/25940

**Comment by AustinSchuh** [comment]
It feels like for gtest and google benchmark for the tests and examples, the most reasonable answer is to link against a version downloaded with cmake or bazel.  Those are the easy ones since none of the dependencies should be linking against those anyways.  I think using cmake/bazel to fetch the dependencies is better than submodule.  In a larger project depending on Ceres, there is likely already a version of absl in use, and including another one has the potential to cause conflicts.

We have more options for absl.  As a thought experiment, here's the ones I see:
1) Use cmake to pick absl or glog/gflags at compile time.  This enables projects dependent on ceres to drop glog/gflags for absl, but requires the least common denominator feature set for everything.
2) Vendor in absl rather than using the OS version.
3) Require a minimum version of the OS version of absl.
4) See if it is possible to write some code which adds the VLOG feature to an old install of absl.

I did a bit of digging.  https://chromium.googlesource.com/external/github.com/abseil/abseil-cpp/+/7b6c17e378224844d8663a410da2da5353b205b9 adds VLOG.  It landed on Tue Dec 05 15:07:49 2023.  So [20240116.1](https://github.com/abseil/abseil-cpp/tree/20240116.1) is the first release which has it.

Ubuntu is on 20230802.1-4 (https://launchpad.net/ubuntu/+source/abseil) for oracular, and 20220623.1-3 for noble.

Debian bookworm (stable) is on 20220623.1-1, trixie is on 20230802.1-4, sid is on 20230802.1-4 and experimental is on 20240116.2-2.

My understanding of how packaging works for distributions is that they don't update versions of packages for already released releases, and they don't grab non-released versions (generally).  So, while that goes for absl, it also goes for Ceres.  20240116.1 is ~6 months old now, and is already packaged for Debian experimental.  They will likely stick on the 2.2 release until a 2.3 is ready, and then there will be a delay packaging it from there.

It looks like absl enables symbol namespace versioning by default so multiple versions of Absl can co-exist in 1 binary.

```
austin[236509] aschuh-3950x ((20240116.2)) ~/local/abseil-cpp/absl/log
$ grep -R 20220623 /usr/include/absl/
/usr/include/absl/base/config.h:#define ABSL_LTS_RELEASE_VERSION 20220623
austin[236510] aschuh-3950x ((20240116.2)) ~/local/abseil-cpp/absl/log
$ grep -R debian3 /usr/include/absl/
/usr/include/absl/base/options.h:#define ABSL_OPTION_INLINE_NAMESPACE_NAME debian3
```

Ironically, the place this falls apart is flags...

```
austin.schuh[18246] lt14-aschu001 /tmp/absl_deb/usr/lib/x86_64-linux-gnu
$ objdump -tTC libabsl_log_flags.so.20240116

libabsl_log_flags.so.20240116:     file format elf64-x86-64


DYNAMIC SYMBOL TABLE:
0000000000000000      DO *UND*  0000000000000000 (CXXABI_1.3) typeinfo for int
0000000000000000      DF *UND*  0000000000000000  Base        absl::debian6::flags_internal::FlagImpl::Read(void*) const
0000000000000000      DF *UND*  0000000000000000  Base        absl::debian6::log_internal::UpdateGlobalVLogLevel(int)
0000000000000000  w   DF *UND*  0000000000000000 (GLIBC_2.2.5) __cxa_finalize
...
00000000000072a6 g    DO .bss   0000000000000001  Base        FLAGS_nostderrthreshold
```

On Debian, not much depends on absl:
```
root@a0ff01396512:/# apt-cache rdepends libabsl20230802
libabsl20230802
Reverse Depends:
  bear
  protobuf-compiler
  libprotoc25
  libprotobuf25
  libprotobuf-lite25
  clangd-19
  libreoffice-core-nogui
  libreoffice-core
  ycmd
  telegram-desktop
  sra-toolkit
  libre2-11
  libqt6grpc6
  open-vm-tools-containerinfo
  uim-mozc
  mozc-utils-gui
  mozc-server
  ibus-mozc
  fcitx5-mozc
  fcitx-mozc
  emacs-mozc-bin
  clangd-18
  clangd-17
  clangd-16
  clangd-15
  clangd-14
  libreoffice-core-nogui
  libreoffice-core
  libphonenumber8
  libgeocoding8
  libgav1-bin
  libgav1-1
  python3-grpcio
  libgrpc29t64
  libgrpc++1.51t64
  fastnetmon
  python3-dm-tree
  collectd-core
  collectd
  libear
  libabsl-dev
root@a0ff01396512:/# apt-cache rdepends libabsl20240116
libabsl20240116
Reverse Depends:
  libabsl-dev
```

Given all this, I think the only reasonable answer is to build a copy of absl from source if the one on the system is either too old, or doesn't exist.  Package maintainers can update absl (might want a flag to force using the system one) without an issue to link against the system one.  This would only be a problem if someone wanted the latest Ceres but the installed protobuf, for example, and protobuf uses flags.  (I didn't check if any of those dependencies actually use flags, or something else)  This is sounding to me more and more like an edge case not worth supporting short term.  And, in 6 months to a year, this will go away as 20240116 or later rolls out wider.

I ran this by some other folks and they were pretty well aligned.

**Comment by sandwichmaker** [comment]
cc: @sergiud 

@AustinSchuh first of all, thank you the thorough investigation of this issue and reporting on it. This is way better than anything I would have done.

so if I understand your proposal, you are proposing that

1. GoogleTest & GoogleBenchmark should use a downloaded version.  I am curious why you think downloading is better than using a submodule. 
2. For ABSL given the availability of ABSL_OPTION_INLINE_NAMESPACE_NAME, we should use a downloaded/submodule version with that name set to something ceres unique/specific so it does not conflict with anything else with an option to use the version of ABSL thats installed on the system -- there we can check against a minimum version to make sure that the build will actually succeed.

For GoogleTest I have a submodule based CL in flight

https://ceres-solver-review.git.corp.google.com/c/ceres-solver/+/26000

@sergiud what do you think? I think if we can come up with a consistent plan here, it would be good to re-work the googletest/benchmark/absl dependencies in consistent manner.

**Comment by AustinSchuh** [comment]
@sandwichmaker , my logic for why to use a downloaded version is pretty simple.  For the 2 repositories I use ceres in, both built with Bazel, we have versions of GoogleTest, GoogleBenchmark, and ABSL already in use and downloaded.  I would rather use those.  Those are modern enough for Ceres, and if they aren't, I would rather update the global version in use.  We used to subtree a bunch of our dependencies in to the repository and have been slowly converting those back to `http_archive`, ie downloaded.  The main reason we found to subtree was if we wanted to be easily able to patch the repository, which I don't think applies here.

That sounds like a good summary!  If it isn't too hard, I would propose a small tweak of linking against the system ABSL if it meets a minimum version check, otherwise falling back to downloading one.  I think a good end goal once ABSL versions progress far enough in distributions is to not introduce extra symbols/versions through Ceres in the happy path.

**Comment by sandwichmaker** [comment]
sorry about the corp link,  the following should work: 

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/26000

This is a version of the CL which is based on using a submodule. But it has an interesting quirk that we have to force include paths in a certain way otherwise an older version of gtest installed on the system can cause problems. Also I still need to respond to the comments on the CL, so do not worry about reviewing it, I just wanted to show you what was one of the alternatives for googletest I was exploring.

With regards to download vs submodule, I am curious to hear what @sergiud thinks.

**Comment by sandwichmaker** [comment]
Couple more questions.

1. How does the absl internal name space wrangling work without editing the
options.h file? Since some of the functions are in the headers.

2. I understand the use case where you are building your own binary and
deploying it. How does this interact with installing Ceres Solver  on a
system with existing or no existing installs of the dependent libraries?

**Comment by AustinSchuh** [comment]
(I'm going to be out of communcation range starting in a couple of hours, will be back in a week on Monday.)

1) That shouldn't matter.  There will only be a symbol collision if the version being downloaded matches the version installed on the system.  In that case, we should pick the system version and not download one so there is no collision.

```
namespace absl {
ABSL_NAMESPACE_BEGIN
```
So every function, including inline ones, is versioned.

2) (going to have to get back to you on this one, I'm out of time :( )

**Comment by sergiud** [comment]
> my logic for why to use a downloaded version is pretty simple. For the 2 repositories I use ceres in, both built with Bazel, we have versions of GoogleTest, GoogleBenchmark, and ABSL already in use and downloaded.

I believe you mix multiple loosely related issues here that we need to better delineate. For this, we can disregard the scenario where the host system already provides compatible dependencies and Ceres can compile against these without building a local version. With this in mind, the above view is still very Bazel centric. Yet, Bazel's concepts do not necessarily transfer to CMake (and vice versa) and that is why Bazel's caching mechanism you are hinting at would not work in a CMake build.

Given all this, fetching dependencies does not provide any benefits over submodules. In particular:
1. Each Git [worktree](https://git-scm.com/docs/git-worktree) and CMake build directory would require redownloading dependencies resulting in unnecessary redundancy.
2. Configuring the build without internet access (or inaccessible repositories, e.g., due to downtime) would not be possible. With submodules, this would not be an issue if the Ceres repository was previously cloned [recursively](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt-code--recurse-submodulescodecodecodeemltpathspecgtem), i.e., by including its submodules.
3. Submodules allow to easily [redirect URLs](https://git-scm.com/docs/git-config/#Documentation/git-config.txt-urlltbasegtinsteadOf), e.g., to a working one in case of a network failure or a version already available locally to avoid repeatedly cloning the repository.
4. Submodules avoid redundancy whenever users intend to use system dependencies since Git does not initialize submodules by default.

**Comment by sandwichmaker** [comment]
Thanks Sergiu. Same question for you as Austin. As far as gtest and
benchmark goes, submodules or fetch is fine since they are not exposed to
the user. But what about absl?

IMO we can only do an install on a system where there is an existing
compatible version of absl no? There is no way to install Ceres where it is
built against a submodule version of absl.

Because this would require installing absl headers.

**Comment by sergiud** [comment]
We could take the same approach as TensorFlow/Lite and install public dependencies in Ceres' include tree. This is of course not ideal as this does not prevent issues with multiple versions of absl. However, if users choose to employ and install local dependencies we can only assume they know what they are doing.

**Comment by sandwichmaker** [comment]
Well absl provides a namespace mangling mechanism for that. That maybe the
way to do it.

**Comment by sergiud** [comment]
Indeed that helps. Conflicts due to local dependencies would be unlikely.

**Comment by sandwichmaker** [comment]
That sounds like a reasonable idea.

**Comment by sandwichmaker** [comment]
@sergiud : 

Would it be reasonable to use submodules for the cmake build and downloading for bazel build? or is that going to lead to inconsistencies/confusion? I imagine we can use some bazel build flags to switch between the two behaviors giving the user flexibility there.

I am not familiar with the cmake conventions of gymnastics around doing the installation. Would it be reasonable that I do the work around adding the submodules for googletest & absl and then you can take over the install and CI wrangling?

**Comment by sergiud** [comment]
I cannot currently think of any problems that could arise from different integration approaches. If fetching dependencies in Bazel is the recommended method then we should probably go with it.

Finishing installation and CI support in a subsequent CL sounds good to me.

**Comment by sandwichmaker** [comment]
Here is the latest version of this change 

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/26041

**Comment by AustinSchuh** [comment]
I've run into enough problems with submodule not updating as well that I'm not a huge fan.  But, I'm a user here, and will be consuming the repository via a tarball.  (We use subtree instead.)  I don't have much of a horse in the race as long as `bazel test @com_google_ceres_solver//...` works :)

The only concern I would have between submodule for cmake and fetching for Bazel inside the ceres-solver repository is the two diverging and it being annoying to debug.  Otherwise, sounds good.

Holler if you want any help on the bazel side, or someone to try it out.  My cmake is pretty weak.  Comments in the review!

**Comment by sandwichmaker** [comment]
This is done, closing.
