### ISSUE TITLE
build error!!

### ISSUE THREAD

**Issue by feiyu12138** [ceres-solver/ceres-solver#803]
Hey, 
When I build ceres, I got a trouble as follows:

CMake Error at internal/ceres/CMakeLists.txt:145 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_cholesky_test>

  No target "cuda_dense_cholesky_test"

totally having no idea, please give me a hand !

**Comment by sandwichmaker** [comment]
cc: @joydeep-b 
can you share what your cmake configuration log looks like?

**Comment by joydeep-b** [comment]
Interesting. 
The target is defined in [internal/ceres/CMakeLists.txt:465](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/CMakeLists.txt#L465).

Yes, @feiyu12138 could you please share the output of running cmake?

**Comment by sandwichmaker** [comment]
closing because of lack of response.

**Comment by Greywan** [comment]
I had the same problem:
`cmake ../ceres-solver-2.1.0`

CMake Error at internal/ceres/CMakeLists.txt:141 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_qr_test>

  No target "cuda_dense_qr_test"


CMake Error at internal/ceres/CMakeLists.txt:145 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_cholesky_test>

  No target "cuda_dense_cholesky_test"

**Comment by joydeep-b** [comment]
@Greywan can you please share the full CMake output?

**Comment by DarlingHang** [comment]
I met similar problem. The output is:

`-- Detected Ceres version: 2.1.0 from /data/xinhang/colmap/ceres-solver-2.1.0/include/ceres/version.h
-- Detected available Ceres threading models: [CXX_THREADS, OPENMP, NO_THREADS]
-- Found Eigen version 3.3.7: /usr/local/share/eigen3/cmake
-- Enabling use of Eigen as a sparse linear algebra library.
-- Found CUDA version 11.2: /usr/local/cuda/lib64/libcudart_static.a;Threads::Threads;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/local/cuda/lib64/libcusolver.so;/usr/local/cuda/lib64/libcusparse.so
-- Found LAPACK library: /usr/lib/libopenblas.so;-lpthread;-lm;-ldl
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found SuiteSparse 4.4.6, building with SuiteSparse.
-- Found CXSparse version: 3.1.4, building with CXSparse.
-- Building without Apple's Accelerate sparse support.
-- Use of gflags disabled - no tests or tools will be built!
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Google Log (glog). Assuming glog was NOT built with gflags support as gflags was not found.  If glog was built with gflags, please set the gflags search locations such that it can be found by Ceres.  Otherwise, Ceres may fail to link due to missing gflags symbols.
-- Using Ceres threading model: CXX_THREADS
-- Building Ceres as a static library.
-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
-- Enabling CERES_NO_ACCELERATE_SPARSE in Ceres config.h
-- Enabling CERES_USE_CXX_THREADS in Ceres config.h
-- Build the examples.
-- Configuring done
CMake Error at internal/ceres/CMakeLists.txt:141 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_qr_test>

  No target "cuda_dense_qr_test"


CMake Error at internal/ceres/CMakeLists.txt:145 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_cholesky_test>

  No target "cuda_dense_cholesky_test"


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by joydeep-b** [comment]
I believe this is a duplicate of #840 , and it should be fixed at HEAD. Please try the latest version from the master branch.
