### ISSUE TITLE
Correctness of covariance

### ISSUE THREAD

**Issue by fyj404** [ceres-solver/ceres-solver#838]
When I used ceres covariance in the vins slam BA problem, I found that even the estimated parameter values were quite different from the true values,but the optimization is still 'confident' enough to give me a low covariance estimate.

**Comment by fyj404** [comment]
The optimizer provides a covariance of 1e-6

**Comment by alexsmac** [comment]
As we explain in the documentation for Covariance [here](http://ceres-solver.org/nnls_covariance.html), using (J^T * J)^{-1} is only the covariance if the errors in all of the residuals are distributed according to a standard Normal, i.e: N(0, I).  If that is *not* the case, which depends on your problem and how you set up your CostFunctions, but is almost never the case in practice, then the result is not mathematically the true covariance.  The best-case scenario is that it is a scaled version.  If your errors are not distributed according to a Gaussian distribution, then not even that will be true.

You should think of the result of (J^T * J)^{-1} as providing only an indication of the relative shape of your overall objective at the evaluation point (usually the termination point of the optimisation).  If your problem is non-convex, this measure will only refer to the local minima where the solver terminated, it will not provide any information or indication of the overall shape of your objective outside of that

**Comment by fyj404** [comment]
> 

Thank you very much. I still need to learn more
