### ISSUE TITLE
findGlog does not always define glog::glog

### ISSUE THREAD

**Issue by KrisThielemans** [ceres-solver/ceres-solver#845]
When using a `CONFIG`, Glog defines the `glog::glog` target, which is recommended to use. However, when searching for the files "by hand", this target is not defined.

**Comment by alexsmac** [comment]
This was intentional, Ceres does not provide the `glog::glog` target when we have to resort to using a module to avoid confusion with the real glog target, and as `IMPORTED` targets cannot themselves then be (re)exported.  Ceres only uses `GLOG_INCLUDE_DIRS` and `GLOG_LIBRARIES` (which are "" and glog::glog respectively when using an exported glog config) when specifying glog as a link dependency.  What issue did you encounter with the current setup?

We will retire support for the legacy (i.e. non-CMake-exported) version of glog when our minimum supported Ubuntu version updates to 22.04 in April 2024 (or the default glog package in 20.04 is updated to include it).

**Comment by KrisThielemans** [comment]
> What issue did you encounter with the current setup?

We use this `FindGlog.cmake` in our own project (not Ceres). https://github.com/UCL/pet-rd-tools. We use `glog::glog` as it is the best way to pass options etc, but this fails to build for people who installed Google on Ubuntu (at least up to 20.04) via APT, as it doesn't supply the glog config) #846 is a simple addition that helped us, but I understand if you don't want to merge it for Ceres.

**Comment by KrisThielemans** [comment]
Thanks @sergiud, that's indeed what we do. (By the way, I like L310 to avoid having some `if` in the config file.).

**Comment by sandwichmaker** [comment]
This is now fixed at head.
