### ISSUE TITLE
Slow CGNR on older Nvidia GPUs

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#870]
On nvidia GPUs like Quadro K2200, CGNR is slower on CPU. The reason it appears is the slow performance of A'x when A is a compressed row sparse. The slowdown does not affect more recent GPUs with compute capability 7.5+. K2200 has compute capability 5.0.

Making a second copy of A and transposing it, seems to alleviate a good chunk of this slowdown at the cost of doubling the memory usage.

**Comment by sandwichmaker** [comment]
cc: @joydeep-b

**Comment by sandwichmaker** [comment]
cc: @DmitriyKorchemkin

**Comment by joydeep-b** [comment]
There is test code that demonstrates that in principle it is possible to create a second copy of the matrix to accelerate leftmultiply on older GPUs: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/22560

However, for this change to be actually useful, we need a use that that satisfies all of the following:

1. A problem that is faster solved using CGNR on GPU than other means (e.g. direct factorization)
2. A problem small enough that the GPU can fit 2x the problem
3. The application needs an older GPU that has this problem (the newer GPUs do not suffer from this slowdown)

Is there a real use case that satisfies all the above? 

The other problem is that doing this will adversely affect problems where CGNR is indeed the best solution (e.g. very large sparse problems on the beefiest GPUs you can get your hands on): by doubling the memory usage, the largest problems will be out of reach.
Because of this issue, if this is implemented, I think it should be disabled by default, and under user control with a linear solver option.

**Comment by sandwichmaker** [comment]
Going to close this as there is no plan to work on this.
