### ISSUE TITLE
The matrices used in spmv_benchmark are not reflective of reality

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#902]
As @DmitriyKorchemkin observes during the development of parallelized left multiply, the performance improvements in the benchmark are not reflected in actual performance on BAL problems. Quoting him:

> While testing a simple approach to parallelization of left multiplications on the BAL dataset, I've found that results do not follow along results of spmv_benchmark.
> I think that this is due to significantly different sparsity pattern column-wise:
> 
> In real data most points have single-digit number of projections and number of points with a certain projection count decreases rapidly
> In our benchmark with point-camera association being distributed according to Bernoulli distribution, number of projections is distributed by binomial distribution. With 1000 cameras and 0.1 visibility probability this gives [82, 119] 95% confidence interval for number of projections per point.
> 

The random matrix generation routines used in spmv_benchmark for bundle adjustment problems should be updated to reflect more realistic matrices.

**Comment by DmitriyKorchemkin** [comment]
Might make sense to make another benchmark similar to `eval_benchmark`, where we just load BAL data from user-provided paths.

The problem was not evident when we were optimizing right multiplications because all rows in BA problems are "uniform" (contain 1 point block and 1 camera block), while in case of left multiplications the difference between columns might be very dramatic.

In our current generator both points and cameras will have number of observations being distributed with binomial distribution, which seem to be dissimilar to real distribution observed in BAL, where both observations/point and observations/camera distributions are skewed towards zero (and there are entries relatively close to 0, while in synthetic data all entries are far from zero).

# Observations per point distributions

![Projections per point distributions](https://user-images.githubusercontent.com/6394216/197556335-7442c6aa-9d93-40f7-882f-8fa9a29f48f5.png)


# Observations per camera distributions
_Note: plots in this section have very different x-axis intervals_

Synthetic:
![Observations per camera synthetic](https://user-images.githubusercontent.com/6394216/197556560-92ab82fc-ff46-442f-bb47-981122a9f465.png)

Real:
![obs_per_camera_real](https://user-images.githubusercontent.com/6394216/197556800-a5d36b80-f905-478a-a5b1-055b5f350df9.png)

**Comment by sandwichmaker** [comment]
This is now fixed at head, @DmitriyKorchemkin has updated evaluation_benchmark to address this.
