### ISSUE TITLE
Turn off housekeeping in optimization code.

### ISSUE THREAD

**Issue by nemeshnorbert** [ceres-solver/ceres-solver#923]
This is a feature request.  It would be nice to have a flag that turns off all data collection into summary structure. For optimization routines that work quite fast most of the time is spent in iteration info collection and housekeeping. When the code is double checked and works just fine I would like to improve performance by not collecting the data inside `summary` structure.

**Comment by sergiud** [comment]
Did you run any benchmarks that confirm the claimed performance gains?

**Comment by alexsmac** [comment]
How big is your problem?  It is very unusual for the iteration summary capture to even be a rounding error on the overall solve time (usually residual evaluation and the linear solver dominate), so it sounds like your problem is very small.  If that is the case, then [TinySolver](https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/tiny_solver.h) might be a better fit for your use-case, as that is explicitly optimised for solving small problems quickly

**Comment by sandwichmaker** [comment]
What sized probleme are you solving? What fraction of your time is going
into summary data collection? Can you share a profile?

**Comment by sandwichmaker** [comment]
closing because of lack of updates. please reopen as needed.
