### ISSUE TITLE
Any reason to make AutoDiffCostFunction final?

### ISSUE THREAD

**Issue by huangqinjin** [ceres-solver/ceres-solver#927]
It broke my code.

```cpp
struct MyCostFunctor
{
    template<typename T>
    bool operator(...) {}
};

class MyCostFunction : MyCostFunctor, public ceres::AutoDiffCostFunction<MyCostFunctor, ...>
{
public:
    MyCostFunction(...) : MyCostFunctor{...}, AutoDiffCostFunction(this, ceres::DO_NOT_TAKE_OWNERSHIP)
    {
    }
};

ceres::CostFunction* cost_function = new MyCostFunction(...);
```

**Comment by huangqinjin** [comment]
To reduce one memory allocation compared to

```cpp
ceres::CostFunction* cost_function = new ceres::AutoDiffCostFunction(new MyCostFunctor);
```

**Comment by sandwichmaker** [comment]
Your functor has no data? So a default construction works? In which case is
memory use of these functors actually a problem?

**Comment by sergiud** [comment]
It can be safely assumed that `AutoDiffCostFunction` constructors never throw because the default `std::vector` constructor throws iff the [default allocator constructor throws](https://en.cppreference.com/w/cpp/container/vector/vector) (guaranteed since C++17). The default allocator constructor is `noexcept` since C++11 though.

The preferred approach here (and in genaral) is to use delegation (over multiple inheritance) by deriving `MyCostFunction` directly from `SizedCostFunction` and defining `AutoDiffCostFunction` and `MyCostFunctor` as member variables of `MyCostFunction` and delegate the calls. Multiple inheritance is known for causing subtle issues that may be hard to identify.

**Comment by huangqinjin** [comment]
AutoDiffCostFunction constructors never throw but the `new` itself may throw `std::bad_alloc`.

The "preferred" approach is not optimal: double vptr, double indirect calls.

> Multiple inheritance is known for causing subtle issues

Only for OOP.

Here the case is simple. It is the [Base from Member](https://www.boost.org/doc/libs/1_80_0/libs/utility/doc/html/utility/utilities/base_from_member.html) idiom.

**Comment by sergiud** [comment]
> AutoDiffCostFunction constructors never throw but the `new` itself may throw `std::bad_alloc`.

You can use `std::make_unique` with post `.release()` if you are convinced this can cause actual problems. The long-term goal, however, is to switch to smart pointers in Ceres' public API.

> The "preferred" approach is not optimal: double vptr, double indirect calls.

Not optimal in what sense? Can you provide any measurements that substantiate this claim?

> Here the case is simple. It is the [Base from Member](https://www.boost.org/doc/libs/1_80_0/libs/utility/doc/html/utility/utilities/base_from_member.html) idiom.

The top priority here is to prevent misuse and subsequent problems even if this means that certain idioms cannot be used anymore. Since there's a straightforward (more explicit and better to understand) solution, I personally don't see any practical issue here.

**Comment by sergiud** [comment]
Another approach that would eliminate the need of the above idiom altogether is to provide a `AutoDiffCostFunction` variant that allows to freely choose the cost functor holder, similar to `ProductManifold`, e.g.,
```cpp
AutoDiffCostFunction2<std::unique_ptr<MyCostFunctor>, ...> a;
AutoDiffCostFunction2<std::shared_ptr<MyCostFunctor>, ...> b;
AutoDiffCostFunction2<MyCostFunctor, ...> c;
```
With C++17 deduction guides we might even be able to eliminate the need of manually specifying sizes of parameter blocks and of the result by extracting the extents of the overloaded `op()` in case these are explicitly given:
```cpp
struct MyCostFunctor
{
    template<class T>
    bool operator(const T p1[5], const T p2[6], T result[2]) { }
};
```
@sandwichmaker What do you think?

**Comment by sandwichmaker** [comment]
Sure in which case it would be good to look at autodiff, numericdiff and
all the related functions at the same time.

**Comment by sergiud** [comment]
Makes sense. Let me close this issue then. I've created #929 for further discussion.
