### ISSUE TITLE
Is the pose_graph_2d_error_term in Ceres equivalent to the edge_se2.cpp in g2o?

### ISSUE THREAD

**Issue by arenas7307979** [ceres-solver/ceres-solver#973]
**--------------------------------------**
pose_graph_2d_error_term ceres version : 
![image](https://user-images.githubusercontent.com/5019568/237025285-1b63bae0-1898-47f3-b39d-93dc0c7777d6.png)
translation residual term  r_a^T * (p_b - p_a) - \hat{p_ab} 
**--------------------------------------**
g2o edge_se2.cpp version : 
![image](https://user-images.githubusercontent.com/5019568/237025612-c78e0d11-2415-447d-9f40-eec94f6452b3.png)

According to the Jacobian in edge_se2.cpp, the translation residual term is Rba_obs * (Rwa.transpose() * (twb-twa)) + tba_obs.

Why Ceres missing Rba_obs?

**Comment by sandwichmaker** [comment]
I am not sure, as I am not the original author of this code. @mvitus should be able to answer.

**Comment by mvitus** [comment]
The ceres formulation isn't missing Rba_obs. 

The displacement from node A to node B, p_ab, is in frame A. p_b and p_a are in the world frame.  So r_a^T transform the displacement from node A to node B from the world frame to frame A.  To use a more clear notation:

r_a^T * (p_b - p_a) - \hat{p_ab}

 should be
 
 w_r_a^T * (w_p_b - w_p_a) - \hat{a_p_ab}
 
 In the g2o formulation they have the term Rba_obs to transform the displacement from a to b in frame A, i.e. a_p_ab, to an observation, obs, frame. 
 
 It has been a really long time since I looked at their code but I have a slight recollection that Rba_obs is identity in their code.
