### ISSUE TITLE
Error LNK2019 unresolved external symbol

### ISSUE THREAD

**Issue by Tomta10** [ceres-solver/ceres-solver#985]
My Ceres project still has issues, mainly Ceres and Cuda_ Block_ Spark_ CRs_ View_ Two sub projects of test encountered unresolved symbols, and this issue has been reported with error ceres_ Static debug lib and cuda_ Block_ Spark_ CRs_ There seems to be a strange issue with view.obj. I hope someone can provide help.
![image](https://github.com/ceres-solver/ceres-solver/assets/98038949/c24a6077-6034-40bf-9842-47696c8c55a0)

**Comment by Tomta10** [comment]
This unresolved symbol is related to the functions ceres:: internal:: FillCRSStructure and ceres:: internal:: PermuteToCRS, which prevents me from regenerating ceres and cuda in vs2022_ Block_ Spark_ CRs_ View_ Test these two sub projects

**Comment by sandwichmaker** [comment]
@Tomta10 can you describe your build environment? are you building with CUDA support enabled>

**Comment by sandwichmaker** [comment]
cc: @DmitriyKorchemkin

**Comment by DmitriyKorchemkin** [comment]
@sandwichmaker , this can be reproduced via our Github Actions CI.

The problem (I guess; don't know how windows works tbh) is in windows compiler hiding symbols by default and linux compiler exposing symbols by default. Since we build cuda stuff into a separate library - it fails at the linkage step on windows.

I suppose that this was not(?) a problem before because only block-sparse kernels use `Block` and `Cell` structures, and with those we get dll export / import attributes via headers, which makes msvc decide to not expose symbols [this statement is just guesswork].

Once we merge
  - Jason's fix for CMake on windows: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/24280
  - Fix for `ceres_cuda_kernels`:  https://ceres-solver-review.googlesource.com/c/ceres-solver/+/24520
  - Github actions workflow with CUDA support for windows: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/24500
  
 the code builds on CI (and hopefully runs on windows as good as it does on linux; I don't have a windows box to test it).

**Comment by sergiud** [comment]
> in windows compiler hiding symbols by default and linux compiler exposing symbols by default

No, it's not.

https://github.com/ceres-solver/ceres-solver/blob/ee90f6cbf7ce6cd91e3b9e8cb8c36f098f1546da/CMakeLists.txt#L73-L75

The behavior is set to be consistent across compilers.

**Comment by sandwichmaker** [comment]
@sergiud what do you think is the cause here then?

**Comment by sandwichmaker** [comment]
and are we sure that Cmake is doing what it says its doing?

**Comment by sergiud** [comment]
Yes, absolutely sure. The behavior is different iff the above options are explicitly overridden which does not seem to be the case here.

It is however puzzling why linking against Ceres suddenly requires access to internal symbols in the first place particularly given a shared library is used. Public API should not depend on such symbols.

**Comment by DmitriyKorchemkin** [comment]
> It is however puzzling why linking against Ceres suddenly requires access to internal symbols in the first place particularly given a shared library is used. Public API should not depend on such symbols.
But the problem is not linking against ceres-solver, but linking ceres-solver itself.

**Comment by sandwichmaker** [comment]
is this still a problem?

**Comment by Tomta10** [comment]
I changed the version of ceres to solve this problem, which should be caused by the incompatibility between vs2022 and the earlier version of ceres. I didn't have any errors when I was in ceres2.2.1.

**Comment by Tomta10** [comment]
@sandwichmaker Replacing the cres version can effectively solve this problem of unresolved instructions, and now the problem has been solved.
