### ISSUE TITLE
Solve with suitesparse failed

### ISSUE THREAD

**Issue by wongshek** [ceres-solver/ceres-solver#995]
Environment:
- ceres 2.0.0
- windows 10
- visualstudio 2019
- c++17

Program crashes when running to internal/ceres/suitesparse.cc L278: `int cholmod_status = cholmod_factorize(A, L, &cc_);`
The error prompt is `Module not found `

I would like to use Intel mkl blas with suitesparse. My cmake configuration is as follows, any issues here?
![image](https://github.com/ceres-solver/ceres-solver/assets/87893723/601f3ac0-8d3d-43db-b370-c75e8bca3ebf)
![image](https://github.com/ceres-solver/ceres-solver/assets/87893723/1cf2f9c5-b689-437e-b21a-eb80f88f50e5)

BTW I add a definition: `add_definitions("-DNOMINMAX")`

**Comment by sandwichmaker** [comment]
@wongshek if you are getting a Module not found error, then I believe something is not right with you SuiteSparse installation. My suspicion is that Ceres uses the super nodal cholesky algorithm and your SuiteSparse/CHOLMOD library was compiled without it perhaps because it is GPL? or requires BLAS/LAPACK unlike the simplicial algorithm which is simpler and lower performance.

**Comment by wongshek** [comment]
Although I still don't know how to configure Ceres with MKL，when I switched to OpenBLAS-0.3.22-x64, everything became normal.

**Comment by sandwichmaker** [comment]
is this issue still open?

**Comment by sandwichmaker** [comment]
closing due to lack of update.
